id=ontoboard
name=OntoBoard
version=${project.version}
download=https://github.com/${github.repo}/releases/download/v${project.version}/ontoboard-${project.version}.jar
readme=https://github.com/${github.repo}/blob/main/README.md
license=https://github.com/${github.repo}/blob/main/LICENSE
author=Ebrahim Norouzi, ISE / FIZ Karlsruhe
