package de.fizkarlsruhe.ise.ontoboard.git;

import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Locale;

/**
 * Which file to open, out of a repository full of them.
 *
 * <p>An ODK repository has one file a person edits and dozens they must not. {@code src/ontology/}
 * holds {@code mwo-edit.owl}, the source of truth; beside it sits {@code mwo.owl}, generated by
 * the build and overwritten by it; under {@code imports/} are a dozen extracted modules; under
 * {@code releases/} is every version ever published. Opening any of them instead of the edit file
 * gives someone a file whose changes will be silently destroyed the next time {@code make} runs.
 *
 * <p>So the order below is not a heuristic for finding "an ontology". It is the ODK convention,
 * followed deliberately, with the generated and derived files ruled out rather than merely ranked
 * lower - because on a repository where the edit file is missing, guessing the release artefact is
 * worse than saying nothing was found.
 *
 * <p>No network, no Swing, no Protege.
 */
public final class RepoLayout {

    /** What OWL API can open, in the forms an OBO project uses. */
    private static final String[] EXTENSIONS = {".owl", ".obo", ".ofn", ".omn", ".ttl", ".owx",
            ".rdf"};

    /** Directories whose contents are never the file to edit. */
    private static final String[] NEVER = {".git", "releases", "imports", "target", "node_modules",
            "build", "tmp", ".github", "docs", "reports"};

    private RepoLayout() {
    }

    /**
     * The ontology to open in this repository, or null when there is nothing to open.
     *
     * @param repository the checkout's root directory
     * @param hintedPath the path from the link the user pasted, or null. A link to a particular
     *     file is a statement about which file, and beats every convention below.
     */
    public static File ontologyIn(File repository, String hintedPath) {
        if (repository == null || !repository.isDirectory()) {
            return null;
        }
        if (hintedPath != null && !hintedPath.trim().isEmpty()) {
            File hinted = new File(repository, hintedPath.trim());
            if (hinted.isFile() && isOntology(hinted)) {
                return hinted;
            }
            if (hinted.isDirectory()) {
                File inThere = bestOf(candidatesUnder(hinted, repository));
                if (inThere != null) {
                    return inThere;
                }
            }
            // A link to something that has moved, or to a README. Fall through to the layout
            // rather than refusing: the repository is still the thing they asked to open.
        }
        return bestOf(candidatesIn(repository));
    }

    /** Every file worth offering, best first. */
    public static List<File> candidatesIn(File repository) {
        return candidatesUnder(repository, repository);
    }

    private static List<File> candidatesUnder(File directory, File repository) {
        List<File> found = new ArrayList<File>();
        collect(directory, found);
        Collections.sort(found, byHowLikelyItIsTheEditFile(repository));
        return found;
    }

    private static File bestOf(List<File> candidates) {
        return candidates.isEmpty() ? null : candidates.get(0);
    }

    private static void collect(File directory, List<File> found) {
        File[] entries = directory.listFiles();
        if (entries == null) {
            return;
        }
        for (File entry : entries) {
            if (entry.isDirectory()) {
                if (!isNeverSearched(entry.getName())) {
                    collect(entry, found);
                }
            } else if (isOntology(entry)) {
                found.add(entry);
            }
        }
    }

    private static boolean isNeverSearched(String name) {
        String lower = name.toLowerCase(Locale.ROOT);
        for (String excluded : NEVER) {
            if (lower.equals(excluded)) {
                return true;
            }
        }
        return lower.startsWith(".");
    }

    static boolean isOntology(File file) {
        String lower = file.getName().toLowerCase(Locale.ROOT);
        for (String extension : EXTENSIONS) {
            if (lower.endsWith(extension)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Best first: the ODK edit file, then any edit file, then the shallowest.
     *
     * <p>{@code -idranges.owl} is ranked last deliberately. It is an ontology, it lives in
     * {@code src/ontology/} beside the edit file, and it is a configuration file nobody edits by
     * hand - so on a repository whose edit file is named unusually it would otherwise win.
     */
    private static Comparator<File> byHowLikelyItIsTheEditFile(final File repository) {
        return new Comparator<File>() {
            @Override
            public int compare(File left, File right) {
                int byRank = Integer.compare(rank(left), rank(right));
                if (byRank != 0) {
                    return byRank;
                }
                int byDepth = Integer.compare(depth(left), depth(right));
                if (byDepth != 0) {
                    return byDepth;
                }
                return left.getName().compareToIgnoreCase(right.getName());
            }

            private int rank(File file) {
                String name = file.getName().toLowerCase(Locale.ROOT);
                String path = relative(repository, file).toLowerCase(Locale.ROOT);
                if (name.endsWith("-idranges.owl")) {
                    return 9;
                }
                boolean inSrcOntology = path.startsWith("src/ontology/");
                if (name.endsWith("-edit.owl") || name.endsWith("-edit.obo")) {
                    return inSrcOntology ? 0 : 1;
                }
                if (inSrcOntology) {
                    return 3;
                }
                return 5;
            }

            private int depth(File file) {
                return relative(repository, file).split("/").length;
            }
        };
    }

    /** A path relative to the repository root, with forward slashes. */
    public static String relative(File repository, File file) {
        try {
            return repository.toPath().toAbsolutePath().normalize()
                    .relativize(file.toPath().toAbsolutePath().normalize())
                    .toString().replace('\\', '/');
        } catch (IllegalArgumentException notUnderneath) {
            return file.getName();
        }
    }

    /**
     * Why this file rather than another, for the result a user reads.
     *
     * <p>Worth saying out loud. An ODK repository has a dozen ontology files and only one of them
     * is the one to edit; a tool that opens one without saying which, or why, leaves someone
     * editing the release artefact and losing the work at the next build.
     */
    public static String explain(File repository, File chosen, List<File> candidates) {
        if (chosen == null) {
            return "No ontology file was found in this repository.";
        }
        String path = relative(repository, chosen);
        if (candidates.size() <= 1) {
            return "Opened " + path + ", the only ontology in the repository.";
        }
        if (path.startsWith("src/ontology/") && path.endsWith("-edit.owl")) {
            return "Opened " + path + " - the ODK edit file, which is the one you change. The "
                    + "other " + (candidates.size() - 1) + " ontology files here are generated by "
                    + "the build or imported from elsewhere.";
        }
        return "Opened " + path + ", chosen from " + candidates.size()
                + " ontology files. This repository does not follow the ODK layout, so check it "
                + "is the file you meant.";
    }
}
