package de.fizkarlsruhe.ise.ontoboard.odk;

import java.io.File;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLImportsDeclaration;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyManager;

/**
 * Which of an ontology's imports actually arrived.
 *
 * <p>An ontology whose imports did not resolve opens perfectly happily. The class hierarchy is
 * there, the file is there, and the several thousand classes it was importing are not - so a term
 * looks unused, a subclass axiom points at nothing, and a reasoner finds no inconsistency because
 * half the axioms are absent. Nothing about the window says so.
 *
 * <p>For an ODK project the cause is nearly always the catalog: the import IRIs are under the
 * project's own domain and have never been published, so unless {@code catalog-v001.xml} maps them
 * to files on disk they resolve to a 404. Which is worth saying in exactly those words, because
 * "could not load imported ontology" sends people to check their network.
 *
 * <p>Read from what the manager already has, so it costs nothing - no second load, no network.
 */
public final class ImportHealth {

    /** An import that is declared but not present. */
    public static final class Missing {
        private final IRI iri;
        private final boolean inCatalog;
        private final boolean fileExists;

        Missing(IRI iri, boolean inCatalog, boolean fileExists) {
            this.iri = iri;
            this.inCatalog = inCatalog;
            this.fileExists = fileExists;
        }

        public IRI getIri() {
            return iri;
        }

        /** Whether the catalog beside the ontology says anything about it. */
        public boolean isInCatalog() {
            return inCatalog;
        }

        /** Whether the file the catalog points at is there. */
        public boolean fileExists() {
            return fileExists;
        }

        /**
         * What to do about this one.
         *
         * <p>Three different problems wear the same error message, and they need three different
         * responses: a catalog that does not mention it, a catalog that points at a file nobody
         * committed, and a remote ontology that simply could not be fetched.
         */
        public String explain() {
            if (inCatalog && fileExists) {
                // Both halves of the mapping are in place, so nothing was fetched and nothing was
                // missing - the file itself did not parse. Sending this user to check their
                // network, as the fallthrough used to, is advice about the one thing that is
                // certainly fine.
                return iri + " is mapped by catalog-v001.xml to a file that is there, so it was "
                        + "found and could not be read. The file is most likely truncated or not "
                        + "valid OWL - open it directly to see what Protege says about it.";
            }
            if (inCatalog && !fileExists) {
                return iri + " is in catalog-v001.xml but the file it points at is not there. It "
                        + "is probably generated by the build and not committed - run 'make' in "
                        + "the project, or 'make imports'.";
            }
            if (!inCatalog && isProjectLocal()) {
                return iri + " has no entry in catalog-v001.xml, and an IRI like that is never "
                        + "published anywhere, so nothing can fetch it. The catalog is what makes "
                        + "it resolve.";
            }
            return iri + " could not be fetched. If you are offline or behind a proxy that is "
                    + "why; otherwise the ontology it names may have moved.";
        }

        /** An import module's IRI, as opposed to a published ontology's. */
        private boolean isProjectLocal() {
            String text = iri.toString().toLowerCase(Locale.ROOT);
            return text.contains("/imports/") || text.startsWith("file:");
        }

        @Override
        public String toString() {
            return iri.toString();
        }
    }

    private ImportHealth() {
    }

    /**
     * The imports that are declared but did not arrive.
     *
     * @param ontology the ontology as opened
     * @param manager the manager that opened it - an import that resolved is in here
     * @param catalog {@code catalog-v001.xml} beside the ontology, or null if there is none
     */
    public static List<Missing> missingFrom(OWLOntology ontology, OWLOntologyManager manager,
            File catalog) {
        List<Missing> missing = new ArrayList<Missing>();
        if (ontology == null || manager == null) {
            return missing;
        }
        String catalogXml = readOrNull(catalog);
        for (OWLImportsDeclaration declaration : ontology.getImportsDeclarations()) {
            IRI iri = declaration.getIRI();
            // getImportedOntology(declaration), NOT contains(iri). An import resolves to whatever
            // document the catalog points at, and that document's own ontology IRI need not equal
            // the IRI in the import statement - which is why OWL API keeps a separate map from
            // declarations to loaded ontologies. Asking contains(iri) instead reports a perfectly
            // resolved import as missing whenever the two differ, and they differ constantly:
            // three of the four import modules in the reference ODK project declare an IRI one
            // path segment away from the one that imports them, and every version-IRI import
            // (.../obo/iao/2022-11-07/iao.owl resolving to a file whose IRI is .../obo/iao.owl)
            // differs by construction. The user was then told the ontology was missing everything
            // those imports contain, while it was all present.
            if (manager.getImportedOntology(declaration) != null) {
                continue;
            }
            String mapped = catalogXml == null ? null
                    : Catalog.entryFor(catalogXml, iri.toString());
            boolean fileExists = mapped != null && catalog != null
                    && catalog.getParentFile() != null
                    && new File(catalog.getParentFile(), mapped).isFile();
            missing.add(new Missing(iri, mapped != null, fileExists));
        }
        return missing;
    }

    private static String readOrNull(File catalog) {
        if (catalog == null || !catalog.isFile()) {
            return null;
        }
        try {
            return new String(Files.readAllBytes(catalog.toPath()), Charset.forName("UTF-8"));
        } catch (java.io.IOException cannotRead) {
            return null;
        }
    }
}
