package de.fizkarlsruhe.ise.ontoboard.odk;

import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

/**
 * Recognises an existing ODK repository and finds the file to open.
 *
 * <p>ODK projects have a conventional shape, and users think in terms of "my ontology repo",
 * not "the file at src/ontology/foo-edit.owl". Asking someone to navigate to the right file
 * inside a tree they may have cloned rather than created is a needless way to lose them, and
 * picking the wrong file - the release artifact rather than the edit file - means their edits
 * get overwritten by the next build.
 *
 * <p>So: point at a repository, and this works out what to open. Detection is deliberately
 * conservative - if it cannot find an unambiguous edit file it says so rather than guessing.
 */
public final class OdkProjectLoader {

    private static final Charset UTF8 = Charset.forName("UTF-8");

    /** What was found in a candidate directory. */
    public static final class Detected {
        private final File projectRoot;
        private final File editFile;
        private final String ontologyId;
        private final String title;

        Detected(File projectRoot, File editFile, String ontologyId, String title) {
            this.projectRoot = projectRoot;
            this.editFile = editFile;
            this.ontologyId = ontologyId;
            this.title = title;
        }

        public File getProjectRoot() {
            return projectRoot;
        }

        /** The `-edit.owl` file, which is the one a modeller edits. */
        public File getEditFile() {
            return editFile;
        }

        public String getOntologyId() {
            return ontologyId;
        }

        /** From the ODK YAML if present, otherwise the ontology id. */
        public String getTitle() {
            return title;
        }
    }

    /** Raised when a directory is not a recognisable ODK project. */
    public static class NotAnOdkProjectException extends RuntimeException {
        private static final long serialVersionUID = 1L;

        NotAnOdkProjectException(String message) {
            super(message);
        }
    }

    private OdkProjectLoader() {
    }

    /**
     * Detects an ODK project at or under {@code candidate}.
     *
     * <p>Accepts either the repository root or {@code src/ontology} itself, because both are
     * reasonable things to select in a file chooser.
     *
     * @throws NotAnOdkProjectException with an actionable message when detection fails
     */
    public static Detected detect(File candidate) {
        if (candidate == null || !candidate.isDirectory()) {
            throw new NotAnOdkProjectException(
                    "Choose a folder, not a file.");
        }
        File ontologyDir = locateOntologyDir(candidate);
        if (ontologyDir == null) {
            throw new NotAnOdkProjectException(
                    "'" + candidate.getName() + "' does not look like an ODK project - no "
                            + "src/ontology folder found. Select the repository root, or the "
                            + "src/ontology folder itself.");
        }

        List<File> editFiles = editFilesIn(ontologyDir);
        if (editFiles.isEmpty()) {
            throw new NotAnOdkProjectException(
                    "Found " + ontologyDir.getPath() + " but no '*-edit.owl' file in it. ODK "
                            + "projects keep the file you edit there; the plain '.owl' file is "
                            + "generated by the build and would be overwritten.");
        }
        if (editFiles.size() > 1) {
            // Opening the wrong one silently means edits land in a file the build regenerates.
            StringBuilder names = new StringBuilder();
            for (File f : editFiles) {
                if (names.length() > 0) {
                    names.append(", ");
                }
                names.append(f.getName());
            }
            throw new NotAnOdkProjectException(
                    "Found more than one edit file (" + names + "). Open the one you want "
                            + "directly with File > Open, so the wrong one is not edited.");
        }

        File editFile = editFiles.get(0);
        String id = editFile.getName().substring(0, editFile.getName().length() - "-edit.owl".length());
        return new Detected(rootOf(ontologyDir), editFile, id, titleFor(ontologyDir, id));
    }

    /** True when {@code candidate} looks like an ODK project, without throwing. */
    public static boolean looksLikeOdkProject(File candidate) {
        try {
            detect(candidate);
            return true;
        } catch (RuntimeException notAProject) {
            return false;
        }
    }

    private static File locateOntologyDir(File candidate) {
        // The chooser may point at src/ontology directly.
        if (containsEditFile(candidate)) {
            return candidate;
        }
        File nested = new File(new File(candidate, "src"), "ontology");
        if (nested.isDirectory()) {
            return nested;
        }
        // Or at src/, one level up from ontology.
        File fromSrc = new File(candidate, "ontology");
        if (fromSrc.isDirectory()) {
            return fromSrc;
        }
        return null;
    }

    private static boolean containsEditFile(File dir) {
        return dir.isDirectory() && !editFilesIn(dir).isEmpty();
    }

    private static List<File> editFilesIn(File dir) {
        File[] found = dir.listFiles();
        if (found == null) {
            return Collections.emptyList();
        }
        List<File> editFiles = new ArrayList<File>();
        for (File file : found) {
            if (file.isFile() && file.getName().endsWith("-edit.owl")) {
                editFiles.add(file);
            }
        }
        // Deterministic, so a two-edit-file project reports the same pair every time.
        Collections.sort(editFiles);
        return editFiles;
    }

    /** Walks up from src/ontology to the repository root, when that shape is present. */
    private static File rootOf(File ontologyDir) {
        File src = ontologyDir.getParentFile();
        if (src != null && "src".equals(src.getName()) && src.getParentFile() != null) {
            return src.getParentFile();
        }
        return ontologyDir;
    }

    /**
     * Reads {@code title:} out of the ODK YAML.
     *
     * <p>Deliberately a targeted line scan rather than a YAML parse: one field is needed, the
     * file belongs to ODK rather than to us, and a malformed or unexpected YAML must never
     * stop a project from opening. Falls back to the ontology id.
     */
    static String titleFor(File ontologyDir, String ontologyId) {
        File yaml = new File(ontologyDir, ontologyId + "-odk.yaml");
        if (!yaml.isFile()) {
            return ontologyId;
        }
        try {
            for (String line : Files.readAllLines(yaml.toPath(), UTF8)) {
                String trimmed = line.trim();
                if (trimmed.startsWith("title:")) {
                    String value = trimmed.substring("title:".length()).trim();
                    if (value.startsWith("\"") && value.endsWith("\"") && value.length() > 1) {
                        value = value.substring(1, value.length() - 1);
                    }
                    if (!value.isEmpty()) {
                        return value;
                    }
                }
            }
        } catch (IOException unreadable) {
            return ontologyId;
        }
        return ontologyId;
    }

    /**
     * The targets this project's Makefile actually offers, most-used first.
     *
     * <p>Previously this opened the Makefile only to check it existed and then returned six
     * hardcoded names. On the reference project {@code ISE-FIZKarlsruhe/mwo} that was wrong in both
     * directions at once: it offered {@code reason} and {@code report}, which that Makefile does
     * not define, and hid the other 39 targets it does - including {@code all_imports} and the
     * {@code mirror-*} rules, which are what an ODK build is for.
     */
    public static List<String> availableTargets(Detected project) {
        if (project == null) {
            return Collections.emptyList();
        }
        return MakeTargets.ordered(MakeTargets.of(project.getEditFile()));
    }
}
