package de.fizkarlsruhe.ise.ontoboard.odk;

import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates an ODK-compatible repository without Docker.
 *
 * <p>The real Ontology Development Kit seeds a repo by running its own image, which means
 * installing Docker before writing a single axiom. That barrier is one of the two the
 * project set out to remove, so the layout is written directly here - the same approach the
 * retired web application took, and the same file tree, so a project generated by either is
 * interchangeable.
 *
 * <p>What is generated is a real ODK workspace: {@code src/ontology} with the edit file,
 * ODK YAML, Makefile pair, catalog, ID ranges and ROBOT report profile, plus SPARQL quality
 * checks, a GitHub Actions workflow and a README. It does not need Docker to be *created*;
 * running its Makefile targets still needs {@code make} and ROBOT on PATH.
 */
public final class OdkScaffold {

    private static final Charset UTF8 = Charset.forName("UTF-8");

    /**
     * The ROBOT the generated CI installs.
     *
     * <p>Matched to the robot-core this plugin embeds, so the quality report a user sees in
     * Protege and the one their CI produces come from the same rules. They are only as matched as
     * somebody keeps them: a test reads the version out of the dependency and fails if these
     * drift apart.
     */
    static final String ROBOT_VERSION = "1.9.8";

    private OdkScaffold() {
    }

    /**
     * Creates the project.
     *
     * @return every file written, in creation order, so the caller can report what happened
     * @throws IllegalArgumentException if the config is invalid or the target already exists
     */
    public static List<File> create(OdkProjectConfig config) {
        config.validate();

        File root = config.getProjectRoot();
        File src = new File(root, "src");
        File ontology = new File(src, "ontology");

        mkdirs(ontology);
        mkdirs(new File(ontology, "imports"));
        mkdirs(new File(src, "metadata"));
        mkdirs(new File(src, "scripts"));
        mkdirs(new File(src, "sparql"));
        mkdirs(new File(src, "patterns"));
        mkdirs(new File(root, "docs"));
        mkdirs(new File(new File(root, ".github"), "workflows"));

        String id = config.getOntologyId();
        List<File> written = new ArrayList<File>();

        // The edit file is what Protege opens.
        //
        // src/ontology/<id>.owl is deliberately NOT seeded. It is what `make reason` produces and
        // what `make clean` deletes, so committing a hand-made copy of the edit file under that
        // name meant every build dirtied the working tree and every clean deleted a tracked file.
        // It is gitignored instead. The artefact that belongs in version control is the one
        // prepare_release copies to the project root, which a PURL can resolve to.
        written.add(write(new File(ontology, id + "-edit.owl"), editOwl(config)));

        written.add(write(new File(ontology, id + "-odk.yaml"), odkYaml(config)));
        written.add(write(new File(ontology, "Makefile"), generatedMakefile(config)));
        written.add(write(new File(ontology, id + ".Makefile"), customMakefile(config)));
        written.add(write(new File(ontology, id + "-idranges.owl"), idRanges(config)));
        written.add(write(new File(ontology, "catalog-v001.xml"), catalog()));
        written.add(write(new File(ontology, "profile.txt"), reportProfile()));
        written.add(write(new File(new File(src, "sparql"), "check_labels.rq"), checkLabels()));
        written.add(write(new File(new File(new File(root, ".github"), "workflows"), "qc.yml"),
                workflow(config)));
        written.add(write(new File(root, ".gitignore"), gitignore(config)));
        written.add(write(new File(root, "README.md"), readme(config)));
        return written;
    }

    private static String editOwl(OdkProjectConfig c) {
        return "<?xml version=\"1.0\"?>\n"
                + "<rdf:RDF xmlns=\"" + c.getNamespace() + "\"\n"
                + "     xml:base=\"" + c.getBaseIri() + "\"\n"
                + "     xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "     xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
                + "     xmlns:dcterms=\"http://purl.org/dc/terms/\">\n"
                + "    <owl:Ontology rdf:about=\"" + c.getBaseIri() + "\">\n"
                + "        <rdfs:label xml:lang=\"en\">" + xml(c.getTitle()) + "</rdfs:label>\n"
                + "        <dcterms:title xml:lang=\"en\">" + xml(c.getTitle()) + "</dcterms:title>\n"
                + "        <dcterms:description xml:lang=\"en\">"
                + xml(c.getDescription()) + "</dcterms:description>\n"
                + (c.getLicense().isEmpty() ? ""
                        : "        <dcterms:license rdf:resource=\"" + xml(c.getLicense())
                                + "\"/>\n")
                + "        <owl:versionInfo>0.1.0</owl:versionInfo>\n"
                + "    </owl:Ontology>\n"
                + "</rdf:RDF>\n";
    }

    private static String odkYaml(OdkProjectConfig c) {
        return "# ODK configuration for " + c.getTitle() + "\n"
                // Not "sh run.sh make update_repo". That is ODK's own instruction and it
                // names a 150-line Docker wrapper around obolibrary/odkfull - which this scaffold
                // deliberately does not write, because running the pipeline without a Docker
                // prerequisite is the reason this plugin embeds robot-core. Telling a user to run
                // a file that does not exist is worse than telling them nothing.
                + "# This project's Makefile calls robot directly, so it needs make and robot on\n"
                + "# PATH - not Docker. Nothing regenerates the Makefile from this file:\n"
                + "# ODK's `make update_repo` is not part of this project. Put your own\n"
                + "# rules in " + c.getOntologyId() + ".Makefile, which the build includes\n"
                + "# and never overwrites.\n"
                + "id: " + c.getOntologyId() + "\n"
                + "title: \"" + c.getTitle() + "\"\n"
                + "description: \"" + c.getDescription() + "\"\n"
                + "uribase: " + uriBase(c) + "\n"
                + (c.getLicense().isEmpty() ? "" : "license: " + c.getLicense() + "\n")
                // Only what the Makefile actually produces. It listed base, full, obo and json
                // before, and built one .owl - so a user following the generated configuration
                // went looking for four artefacts, found one, and had no way to tell whether the
                // build was broken or the configuration was decorative.
                + "release_artefacts:\n"
                + "  - full\n"
                + "primary_release: full\n"
                + "export_formats:\n"
                + "  - owl\n"
                + "import_group:\n"
                + "  products: []\n"
                + "robot_report:\n"
                + "  use_labels: TRUE\n"
                + "  fail_on: ERROR\n"
                + "  report_on:\n"
                + "    - edit\n";
    }

    private static String generatedMakefile(OdkProjectConfig c) {
        String id = c.getOntologyId();
        return "# WARNING: generated by OntoBoard. Do NOT edit by hand.\n"
                + "# Put custom targets in " + id + ".Makefile, which is included below.\n\n"
                + "ONT_ID := " + id + "\n"
                + "ONT := $(ONT_ID)\n"
                + "TODAY := $(shell date +%Y-%m-%d)\n\n"
                // Stated, not inherited from file order. `include` splices the custom
                // Makefile in at this point, so the first target a user wrote there became make's
                // default goal - a bare `make` then built whatever they happened to add first
                // instead of the project. Moving the include below `all` would fix it too, but
                // only until somebody moved it back.
                + ".DEFAULT_GOAL := all\n\n"
                + "-include $(ONT).Makefile\n\n"
                + ".PHONY: all test reason report sparql_test clean prepare_release\n\n"
                + "all: reason report\n"
                + "\t@echo \"Build complete: $(ONT)\"\n\n"
                // reason and sparql_test as well as report, because "test" is what CI runs and
                // what the README tells a user to run. report is SPARQL over the axioms; it never
                // starts a reasoner, so an inconsistent ontology or an unsatisfiable class - the
                // worst thing that can be wrong with an ontology - passed QC green. And the
                // scaffold wrote src/sparql/check_labels.rq while nothing anywhere ran it, so a
                // project advertised a quality check it did not perform.
                + "test: reason report sparql_test\n\n"
                + "reason:\n"
                + "\trobot reason -r ELK -i $(ONT)-edit.owl -o $(ONT).owl\n\n"
                // --fail-on and --labels are passed because the YAML above declares them.
                // They were declared and not passed, so CI did whatever ROBOT defaults to rather
                // than what the project said - and a build that says fail_on: ERROR while not
                // failing on errors is worse than one that says nothing.
                // profile.txt holds every rule ROBOT knows, at ROBOT's own severity, and it must
                // stay free of comment lines - ROBOT's parser reads every line as a level and a
                // rule. Said here because this is a Makefile, where # is a comment, and profile.txt
                // is the one place it cannot be said.
                + "# profile.txt lists every ROBOT report rule at its severity. ROBOT does NOT\n"
                + "# merge it with its defaults - it runs exactly what is in the file, so a rule\n"
                + "# you delete stops running silently. To relax one, change ERROR to WARN or INFO\n"
                + "# rather than deleting the line. Do not put comments in profile.txt: ROBOT has\n"
                + "# no comment syntax there and will refuse to run.\n"
                + "report:\n"
                + "\trobot report -i $(ONT)-edit.owl --profile profile.txt \\\n"
                + "\t  --fail-on ERROR --labels true \\\n"
                + "\t  --output report.tsv --format tsv\n\n"
                // robot verify exits non-zero when a query returns rows, which is what makes a
                // SPARQL file a check rather than a decoration.
                + "sparql_test:\n"
                + "\trobot verify --input $(ONT)-edit.owl --queries ../sparql/*.rq --output-dir .\n\n"
                + "clean:\n"
                + "\t@rm -f tmp_* report.tsv *.bak *.csv $(ONT).owl\n\n"
                + "prepare_release: reason report\n"
                // Dated and stamped, not copied. A release with no owl:versionIRI cannot be
                // cited or pinned by anyone downstream, and an undated copy means each release
                // destroys the last - which is what the previous single cp did.
                + "\t@mkdir -p ../../releases/$(TODAY)\n"
                + "\trobot annotate --input $(ONT).owl \\\n"
                // ProjectIri.stemOf, not the raw base IRI: a base ending in .owl - which is
                // what the wizard defaults to - produced .../obo/mwo.owl/releases/<date>/mwo.owl,
                // a third spelling of the same release. The ID-ranges IRI below already stripped
                // the extension, so the generator disagreed with itself in one file.
                + "\t  --version-iri \"" + ProjectIri.stemOf(c.getBaseIri())
                + "/releases/$(TODAY)/$(ONT).owl\" \\\n"
                + "\t  --annotation owl:versionInfo \"$(TODAY)\" \\\n"
                + "\t  --output ../../releases/$(TODAY)/$(ONT).owl\n"
                + "\t@cp ../../releases/$(TODAY)/$(ONT).owl ../../$(ONT).owl\n";
    }

    private static String customMakefile(OdkProjectConfig c) {
        return "# Custom targets for " + c.getOntologyId() + ".\n"
                + "# This file is never overwritten - put your own rules here.\n";
    }

    /**
     * The ID ranges file, in the shape ODK actually uses.
     *
     * <p>What was here before was wrong rather than merely incomplete: it asserted an
     * invented {@code idrange:has_id_policy} property under the project's own namespace, and
     * declared no IRI prefix, no digit count and no ranges at all. ODK's tooling does not
     * recognise that property, and a project generated from it could not allocate identifiers
     * to anybody - so two collaborators would mint the same identifier by construction. The
     * real format and its four OBO properties are in {@link IdRanges}; the reference file is
     * {@code ISE-FIZKarlsruhe/mwo/src/ontology/mwo-idranges.owl}.
     *
     * <p>One range is allocated up front, to whoever is creating the project. A file with no
     * ranges is what the previous version effectively produced, and it makes the very first
     * minting attempt fail for the one person guaranteed to be there.
     */
    private static String idRanges(OdkProjectConfig c) {
        String id = c.getOntologyId();
        String upper = id.toUpperCase(java.util.Locale.ROOT);
        String base = c.getBaseIri().replaceAll("\\.owl$", "");
        return IdRanges.create(base + "/" + id + "-idranges.owl", upper,
                        IdRanges.prefixFor(c.getBaseIri(), id), 7)
                .withRange(firstEditor(), 1000, 9999)
                .toManchester();
    }

    /**
     * Who the first ID range belongs to.
     *
     * <p>The OS account name: there is nothing better available while scaffolding, and it is at
     * least stable and recognisable to the person it names. They can rename it in the file. What
     * matters is that a range exists at all, so the project can mint from the moment it is
     * created.
     */
    private static String firstEditor() {
        String name = System.getProperty("user.name", "");
        return name.trim().isEmpty() ? "FirstEditor" : name.trim();
    }

    private static String catalog() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
                + "<catalog prefer=\"public\" xmlns=\"urn:oasis:names:tc:entity:xmlns:xml:catalog\">\n"
                + "    <!-- Map import IRIs to local files in imports/ as you add them. -->\n"
                + "</catalog>\n";
    }

    /**
     * The ROBOT report profile: every rule ROBOT knows, at ROBOT's own severity.
     *
     * <p>This used to list seven rules, and that was not a smaller profile - it was a silently
     * emptier one. {@code ReportOperation.getProfile(path)} builds a fresh map from the file and
     * does not merge it with ROBOT's defaults (the bundled {@code report_profile.txt} is read only
     * when no path is given), so a project shipping seven lines ran seven of thirty-two checks.
     * Both this plugin's own quality report and the generated CI read the same file, so both were
     * equally blind, and nothing anywhere said which rules were not running.
     *
     * <p>The rules that were off by omission are the ones that catch exactly the damage several
     * editors do to one ontology: {@code deprecated_class_reference},
     * {@code misused_obsolete_label}, {@code misused_replaced_by}, {@code duplicate_label},
     * {@code duplicate_definition}, {@code illegal_use_of_built_in_vocabulary},
     * {@code multiple_equivalent_class_definitions}, {@code invalid_entity_uri}. Two more were
     * quietly downgraded - {@code missing_label} from ERROR to WARN and {@code multiple_labels}
     * from ERROR to INFO.
     *
     * <p>So: every rule, at ROBOT's level, written out in full. A project that wants a rule
     * relaxed edits this file and can see what it changed; nobody loses a check by never having
     * been told it existed. Kept in step with robot-core by a test that reads ROBOT's own bundled
     * profile, so upgrading the dependency fails the build rather than silently adding a rule
     * nobody runs.
     */
    private static String reportProfile() {
        // NO COMMENTS. ROBOT's profile parser reads every line as "<LEVEL> <rule>" and has no
        // comment syntax, so a leading # is parsed as a reporting level and the run dies with
        // "REPORT LEVEL ERROR '# ...' is not a valid reporting level". An explanatory header here
        // broke `make report` in every project this scaffold produced - proven by running ODK
        // against a generated project rather than by reading the documentation, which does not
        // say so either way. The explanation lives in the Makefile and the README instead, where
        // # is a comment and a person will actually meet it.
        return "WARN\tannotation_whitespace\n"
                + "ERROR\tdeprecated_boolean_datatype\n"
                + "ERROR\tdeprecated_class_reference\n"
                + "ERROR\tdeprecated_property_reference\n"
                + "ERROR\tduplicate_definition\n"
                + "WARN\tduplicate_exact_synonym\n"
                + "WARN\tduplicate_label_synonym\n"
                + "ERROR\tduplicate_label\n"
                + "WARN\tduplicate_scoped_synonym\n"
                + "WARN\tequivalent_pair\n"
                + "WARN\tequivalent_class_axiom_no_genus\n"
                + "ERROR\tillegal_use_of_built_in_vocabulary\n"
                + "WARN\tinvalid_xref\n"
                + "ERROR\tlabel_formatting\n"
                + "ERROR\tlabel_whitespace\n"
                + "INFO\tlowercase_definition\n"
                + "WARN\tmissing_definition\n"
                + "ERROR\tmissing_label\n"
                + "WARN\tmissing_obsolete_label\n"
                + "ERROR\tmissing_ontology_description\n"
                + "ERROR\tmissing_ontology_license\n"
                + "ERROR\tmissing_ontology_title\n"
                + "WARN\tmissing_subset_declaration\n"
                + "INFO\tmissing_superclass\n"
                + "WARN\tmissing_synonymtype_declaration\n"
                + "ERROR\tmisused_obsolete_label\n"
                + "ERROR\tmisused_replaced_by\n"
                + "ERROR\tmultiple_definitions\n"
                + "WARN\tmultiple_equivalent_classes\n"
                + "ERROR\tmultiple_equivalent_class_definitions\n"
                + "ERROR\tmultiple_labels\n"
                + "WARN\tinvalid_entity_uri\n";
    }

    private static String checkLabels() {
        return "# Every class should carry an rdfs:label.\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX owl: <http://www.w3.org/2002/07/owl#>\n"
                + "SELECT ?entity WHERE {\n"
                + "  ?entity a owl:Class .\n"
                + "  FILTER NOT EXISTS { ?entity rdfs:label ?label }\n"
                + "  FILTER (!isBlank(?entity))\n"
                + "}\n";
    }

    private static String workflow(OdkProjectConfig c) {
        return "name: QC\n\n"
                + "on:\n"
                + "  push:\n"
                + "  pull_request:\n\n"
                + "jobs:\n"
                + "  build:\n"
                + "    runs-on: ubuntu-latest\n"
                + "    steps:\n"
                + "      - uses: actions/checkout@v4\n"
                // Pinned, and allowed to fail. "latest" meant CI could move to a ROBOT that
                // reports differently from the one OntoBoard embeds, without anybody deciding to.
                // And without --fail, curl exits 0 on a missing asset and writes the nine bytes
                // "Not Found" into robot.jar - so the step named "Install ROBOT" went green and
                // the failure surfaced later as a corrupt-jar error pointing at the ontology.
                + "      - name: Install ROBOT\n"
                + "        run: |\n"
                + "          curl -fsSL --retry 3 -o robot.jar \\\n"
                + "            https://github.com/ontodev/robot/releases/download/v"
                + ROBOT_VERSION + "/robot.jar\n"
                + "          printf '#!/bin/sh\\nexec java -jar %s/robot.jar \"$@\"\\n' "
                + "\"$PWD\" | sudo tee /usr/local/bin/robot > /dev/null\n"
                + "          sudo chmod +x /usr/local/bin/robot\n"
                + "          robot --version\n"
                + "      - name: Run QC\n"
                + "        working-directory: src/ontology\n"
                + "        run: make test\n"
                // The job summary says how many violations there were; only report.tsv says
                // which. Uploading it is the difference between "QC failed, 3 errors" and knowing
                // what to fix without reproducing the run on your own machine.
                + "      - name: Upload the report\n"
                + "        if: always()\n"
                + "        uses: actions/upload-artifact@v4\n"
                + "        with:\n"
                + "          name: robot-report\n"
                + "          path: src/ontology/report.tsv\n"
                + "          if-no-files-found: ignore\n";
    }

    /**
     * What not to commit: generated output, and nothing else.
     *
     * <p>{@code src/ontology/imports/*.owl} used to be here and it was actively harmful. An import
     * module is not generated output that anyone can reproduce - it is a few dozen axioms this
     * project chose to copy out of a much larger ontology at a particular release, and ODK
     * projects commit them. Ignoring them while committing the catalog entry and the import
     * declaration that point at them produces a repository whose imports resolve for the person
     * who made them and for nobody else: clone it, and the catalog maps an IRI to a file that is
     * not there.
     *
     * <p>That is exactly the failure {@code ImportTermsAction} writes a catalog entry to prevent,
     * reintroduced one directory away. CI would not catch it either - the generated workflow runs
     * {@code make test}, which reports on the edit file without loading its imports.
     */
    private static String gitignore(OdkProjectConfig c) {
        return "# Build products only.\n"
                + "#\n"
                + "# The release artefact - <id>.owl at the project ROOT, written by\n"
                + "# `make prepare_release` - is deliberately not here. That one is the\n"
                + "# product, and ODK projects commit it so a PURL resolves to something.\n"
                + "#\n"
                + "# Import modules under src/ontology/imports/ are not here either. A\n"
                + "# module is not reproducible output: it is a few dozen axioms this\n"
                + "# project chose to copy from a much larger ontology at a particular\n"
                + "# release. Ignore it and the catalog entry beside it points at a file\n"
                + "# nobody else has.\n"
                + "tmp_*\n"
                + "report.tsv\n"
                + "# robot verify writes one CSV per failing query into src/ontology.\n"
                + "src/ontology/*.csv\n"
                + "*.bak\n"
                + "src/ontology/" + c.getOntologyId() + ".owl\n";
    }

    private static String readme(OdkProjectConfig c) {
        String id = c.getOntologyId();
        return "# " + c.getTitle() + "\n\n"
                + c.getDescription() + "\n\n"
                + "IRI: `" + c.getBaseIri() + "`\n\n"
                + "## Editing\n\n"
                + "Open `src/ontology/" + id + "-edit.owl` in Protege. That is the file you\n"
                + "edit; `" + id + ".owl` is generated by the build.\n\n"
                + "## Building\n\n"
                + "From `src/ontology`, with `make` and ROBOT on your PATH:\n\n"
                + "```\n"
                + "make reason   # classify with ELK into " + id + ".owl\n"
                + "make report   # ROBOT quality report -> report.tsv\n"
                + "make test     # what CI runs\n"
                + "```\n\n"
                + "Custom targets go in `" + id + ".Makefile`, which the build includes and\n"
                + "never overwrites. `Makefile` itself is generated - do not edit it.\n\n"
                + "Generated by OntoBoard.\n";
    }

    private static String uriBase(OdkProjectConfig c) {
        String base = c.getBaseIri();
        int lastSlash = base.lastIndexOf('/');
        return lastSlash > 0 ? base.substring(0, lastSlash) : base;
    }

    private static void mkdirs(File dir) {
        if (!dir.exists() && !dir.mkdirs()) {
            throw new UncheckedIOException(
                    new IOException("Could not create " + dir.getAbsolutePath()));
        }
    }

    private static File write(File target, String content) {
        try {
            Files.write(target.toPath(), content.getBytes(UTF8));
            return target;
        } catch (IOException failure) {
            throw new UncheckedIOException(
                    "Could not write " + target.getAbsolutePath(), failure);
        }
    }

    private static String xml(String value) {
        return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
