package de.fizkarlsruhe.ise.ontoboard.odk;

import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates an ODK-compatible repository without Docker.
 *
 * <p>The real Ontology Development Kit seeds a repo by running its own image, which means
 * installing Docker before writing a single axiom. That barrier is one of the two the
 * project set out to remove, so the layout is written directly here - the same approach the
 * retired web application took, and the same file tree, so a project generated by either is
 * interchangeable.
 *
 * <p>What is generated is a real ODK workspace: {@code src/ontology} with the edit file,
 * ODK YAML, Makefile pair, catalog, ID ranges and ROBOT report profile, plus SPARQL quality
 * checks, a GitHub Actions workflow and a README. It does not need Docker to be *created*;
 * running its Makefile targets still needs {@code make} and ROBOT on PATH.
 */
public final class OdkScaffold {

    private static final Charset UTF8 = Charset.forName("UTF-8");

    /**
     * The ROBOT the generated CI installs.
     *
     * <p>Read from {@code ontoboard-build.properties}, which Maven fills in from the single
     * {@code robot.version} property in {@code pom.xml} - the same property that picks the
     * robot-core this bundle embeds. So the version a user's CI installs and the version their
     * Protege reports with cannot drift apart, because there is only one of them.
     *
     * <p>It used to be a second literal here, kept in step with the pom by a test. That works right
     * up until somebody bumps one and not the other between test runs, and the plan's F9 asks for
     * "one embedded ROBOT version, declared once" rather than two that are checked.
     */
    static final String ROBOT_VERSION = buildProperty("robot.version");

    /**
     * One value out of the filtered build properties.
     *
     * @throws IllegalStateException when the resource is missing or was never filtered - both mean
     *     the bundle was built wrongly, and a generated CI that installs ROBOT
     *     {@code ${robot.version}} would fail confusingly much later
     */
    private static String buildProperty(String key) {
        java.io.InputStream in = OdkScaffold.class.getClassLoader()
                .getResourceAsStream("ontoboard-build.properties");
        if (in == null) {
            throw new IllegalStateException("ontoboard-build.properties is not on the classpath; "
                    + "the plugin was built without resource filtering.");
        }
        try {
            java.util.Properties properties = new java.util.Properties();
            properties.load(in);
            String value = properties.getProperty(key);
            if (value == null || value.trim().isEmpty() || value.contains("${")) {
                throw new IllegalStateException("ontoboard-build.properties has no usable " + key
                        + " (got '" + value + "'); Maven resource filtering did not run.");
            }
            return value.trim();
        } catch (java.io.IOException cannotRead) {
            throw new IllegalStateException("Could not read ontoboard-build.properties: "
                    + cannotRead.getMessage(), cannotRead);
        } finally {
            try {
                in.close();
            } catch (java.io.IOException ignored) {
                // Closing a classpath resource cannot usefully fail.
            }
        }
    }

    private OdkScaffold() {
    }

    /**
     * Creates the project.
     *
     * @return every file written, in creation order, so the caller can report what happened
     * @throws IllegalArgumentException if the config is invalid or the target already exists
     */
    /**
     * The files a regenerator may rewrite, as relative path to content.
     *
     * <p>Split out from {@link #create} because Phase 3's regenerator has to render exactly these
     * and no others, and because a second copy of the list would drift from this one. Anything
     * absent is a file somebody owns: see {@link #SEEDED_FILES}.
     *
     * <p>Paths use {@code /} so they read the same on every platform and can be compared in a test.
     */
    public static java.util.Map<String, String> regenerableFiles(OdkProjectConfig config,
            String robotVersion) {
        String id = config.getOntologyId();
        java.util.Map<String, String> files = new java.util.LinkedHashMap<String, String>();
        files.put("src/ontology/Makefile", generatedMakefile(config));
        files.put(".github/workflows/qc.yml", workflow(config, robotVersion));
        files.put(".gitattributes", gitattributes());
        files.put(".gitignore", gitignore(config));
        files.put("README.md", readme(config));
        return files;
    }

    /**
     * The files the scaffold writes once and a regenerator must never touch, and why.
     *
     * <p>Not a detail. Three of these are jointly owned or hold state the generator cannot know:
     *
     * <ul>
     *   <li>{@code <id>-edit.owl} - the user's ontology. Obviously.
     *   <li>{@code <id>.Makefile} - explicitly promised never to be overwritten.
     *   <li>{@code <id>-odk.yaml} - the regenerator's own input. Re-rendering it would discard any
     *       comment or key a user added, which is the file they are meant to edit.
     *   <li>{@code <id>-idranges.owl} - holds every editor's allocated range. The template writes
     *       one range for {@code System.getProperty("user.name")}, so regenerating it on another
     *       machine would replace other people's allocations with the current account's.
     *   <li>{@code catalog-v001.xml} - {@code Catalog.addEntry} writes real import mappings into it.
     *       The template is an empty catalog, so re-rendering would delete them and every robot
     *       call in the build would stop resolving its imports.
     *   <li>{@code profile.txt} - the generated Makefile <em>tells the user to edit this file</em>:
     *       "To relax one, change ERROR to WARN or INFO rather than deleting the line." Re-rendering
     *       it would silently re-arm every rule a project had deliberately relaxed, and their next
     *       CI run would go red for something nobody changed.
     *   <li>{@code src/sparql/*.rq} - the project's own quality checks. The scaffold writes
     *       {@code check_labels.rq} as a starting point; a project edits it and adds more, and
     *       {@code sparql_test} runs whatever it finds.
     * </ul>
     *
     * <p>The four that remain regenerable all announce themselves as generated - the Makefile's
     * first line is "WARNING: generated by OntoBoard. Do NOT edit by hand." A user may still have
     * edited the README or the .gitignore, which is exactly why the action previews the diff and
     * writes nothing unless asked.
     */
    public static java.util.List<String> seededFilesFor(String id) {
        return java.util.Collections.unmodifiableList(java.util.Arrays.asList(
                "src/ontology/" + id + "-edit.owl",
                "src/ontology/" + id + ".Makefile",
                "src/ontology/" + id + "-odk.yaml",
                "src/ontology/" + id + "-idranges.owl",
                "src/ontology/catalog-v001.xml",
                "src/ontology/profile.txt",
                "src/sparql/check_labels.rq"));
    }

    public static List<File> create(OdkProjectConfig config) {
        config.validate();

        File root = config.getProjectRoot();
        File src = new File(root, "src");
        File ontology = new File(src, "ontology");

        // Only directories that receive a file. src/metadata, src/scripts, src/patterns and docs
        // were created empty, and an empty directory advertises a capability that is not there -
        // the same pathology as a YAML key nothing reads. Worse, git does not track empty
        // directories at all, so they did not survive a clone: the scaffold was creating four
        // things that existed on the author's machine and nowhere else.
        //
        // imports/ goes the same way. ImportModules and ImportTermsAction both create it when they
        // write into it, which is the moment it starts meaning something.
        mkdirs(ontology);
        mkdirs(new File(src, "sparql"));
        mkdirs(new File(new File(root, ".github"), "workflows"));

        String id = config.getOntologyId();
        List<File> written = new ArrayList<File>();

        // The edit file is what Protege opens.
        //
        // src/ontology/<id>.owl is deliberately NOT seeded. It is what `make reason` produces and
        // what `make clean` deletes, so committing a hand-made copy of the edit file under that
        // name meant every build dirtied the working tree and every clean deleted a tracked file.
        // It is gitignored instead. The artefact that belongs in version control is the one
        // prepare_release copies to the project root, which a PURL can resolve to.
        written.add(write(new File(ontology, id + "-edit.owl"), editOwl(config)));

        // The seeded ones, which nothing regenerates.
        written.add(write(new File(ontology, id + "-odk.yaml"), odkYaml(config, ROBOT_VERSION)));
        written.add(write(new File(ontology, id + ".Makefile"), customMakefile(config)));
        written.add(write(new File(ontology, id + "-idranges.owl"), idRanges(config)));
        written.add(write(new File(ontology, "catalog-v001.xml"), catalog()));
        written.add(write(new File(ontology, "profile.txt"), reportProfile()));
        written.add(write(new File(new File(src, "sparql"), "check_labels.rq"), checkLabels()));

        // And the regenerable ones, through the same map the regenerator uses - so a file added
        // there is created here too, and the two cannot disagree about what is generated.
        for (java.util.Map.Entry<String, String> file
                : regenerableFiles(config, ROBOT_VERSION).entrySet()) {
            File target = new File(root, file.getKey().replace('/', File.separatorChar));
            mkdirs(target.getParentFile());
            written.add(write(target, file.getValue()));
        }
        return written;
    }

    private static String editOwl(OdkProjectConfig c) {
        return "<?xml version=\"1.0\"?>\n"
                + "<rdf:RDF xmlns=\"" + c.getNamespace() + "\"\n"
                + "     xml:base=\"" + c.getBaseIri() + "\"\n"
                + "     xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "     xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
                + "     xmlns:dcterms=\"http://purl.org/dc/terms/\">\n"
                + "    <owl:Ontology rdf:about=\"" + c.getBaseIri() + "\">\n"
                + "        <rdfs:label xml:lang=\"en\">" + xml(c.getTitle()) + "</rdfs:label>\n"
                + "        <dcterms:title xml:lang=\"en\">" + xml(c.getTitle()) + "</dcterms:title>\n"
                + "        <dcterms:description xml:lang=\"en\">"
                + xml(c.getDescription()) + "</dcterms:description>\n"
                + (c.getLicense().isEmpty() ? ""
                        : "        <dcterms:license rdf:resource=\"" + xml(c.getLicense())
                                + "\"/>\n")
                + "        <owl:versionInfo>0.1.0</owl:versionInfo>\n"
                + "    </owl:Ontology>\n"
                + "</rdf:RDF>\n";
    }

    private static String odkYaml(OdkProjectConfig c, String robotVersion) {
        return "# ODK configuration for " + c.getTitle() + "\n"
                // Not "sh run.sh make update_repo". That is ODK's own instruction and it
                // names a 150-line Docker wrapper around obolibrary/odkfull - which this scaffold
                // deliberately does not write, because running the pipeline without a Docker
                // prerequisite is the reason this plugin embeds robot-core. Telling a user to run
                // a file that does not exist is worse than telling them nothing.
                + "# This project's Makefile calls robot directly, so it needs make and robot on\n"
                + "# PATH - not Docker. Nothing regenerates the Makefile from this file:\n"
                + "# ODK's `make update_repo` is not part of this project. Put your own\n"
                + "# rules in " + c.getOntologyId() + ".Makefile, which the build includes\n"
                + "# and never overwrites.\n"
                + "id: " + c.getOntologyId() + "\n"
                + "title: \"" + c.getTitle() + "\"\n"
                + "description: \"" + c.getDescription() + "\"\n"
                + "uribase: " + uriBase(c) + "\n"
                + (c.getLicense().isEmpty() ? "" : "license: " + c.getLicense() + "\n")
                // The project's own ROBOT version, not the plugin's. Seeded from whatever OntoBoard
                // created the project and read back by the regenerator, so re-rendering qc.yml
                // never silently moves a project onto a different ROBOT because a different
                // OntoBoard happened to run - which would make the regenerated file depend on the
                // tool rather than on the project, and break the one property regeneration needs.
                + "robot_version: " + robotVersion + "\n"
                // Only what the Makefile actually produces. It listed base, full, obo and json
                // before, and built one .owl - so a user following the generated configuration
                // went looking for four artefacts, found one, and had no way to tell whether the
                // build was broken or the configuration was decorative.
                + "release_artefacts:\n"
                + "  - full\n"
                + "primary_release: full\n"
                + "export_formats:\n"
                + "  - owl\n"
                + "import_group:\n"
                + "  products: []\n"
                + "robot_report:\n"
                + "  use_labels: TRUE\n"
                + "  fail_on: ERROR\n"
                + "  report_on:\n"
                + "    - edit\n";
    }

    private static String generatedMakefile(OdkProjectConfig c) {
        String id = c.getOntologyId();
        return "# WARNING: generated by OntoBoard. Do NOT edit by hand.\n"
                + "# Put custom targets in " + id + ".Makefile, which is included below.\n\n"
                + "ONT_ID := " + id + "\n"
                + "ONT := $(ONT_ID)\n"
                + "TODAY := $(shell date +%Y-%m-%d)\n"
                // Every robot call goes through $(ROBOT) so that --catalog is not optional.
                // Without it the catalog beside this file is inert: ROBOT resolves an owl:imports
                // over the network, or fails offline, and the whole point of the catalog entry that
                // "Import terms..." writes is that the import resolves without the network. The
                // scaffold wrote the catalog and then ignored it, so the plugin's own feature was
                // undone by the plugin's own Makefile. Real ODK does exactly this:
                // ROBOT = robot --catalog $(CATALOG).
                + "CATALOG := catalog-v001.xml\n"
                + "ROBOT := robot --catalog $(CATALOG)\n\n"
                // Stated, not inherited from file order. `include` splices the custom
                // Makefile in at this point, so the first target a user wrote there became make's
                // default goal - a bare `make` then built whatever they happened to add first
                // instead of the project. Moving the include below `all` would fix it too, but
                // only until somebody moved it back.
                + ".DEFAULT_GOAL := all\n\n"
                + "-include $(ONT).Makefile\n\n"
                + ".PHONY: all test reason report sparql_test validate_profile clean prepare_release\n\n"
                + "all: reason report\n"
                + "\t@echo \"Build complete: $(ONT)\"\n\n"
                // reason and sparql_test as well as report, because "test" is what CI runs and
                // what the README tells a user to run. report is SPARQL over the axioms; it never
                // starts a reasoner, so an inconsistent ontology or an unsatisfiable class - the
                // worst thing that can be wrong with an ontology - passed QC green. And the
                // scaffold wrote src/sparql/check_labels.rq while nothing anywhere ran it, so a
                // project advertised a quality check it did not perform.
                + "test: reason report sparql_test validate_profile\n\n"
                // --equivalent-classes-allowed asserted-only, because ROBOT's default is
                // EquivalentClassReasoningMode.ALL: a reasoner that concludes two *named* classes
                // are equivalent is almost always reporting a modelling mistake - two terms defined
                // identically, usually by different editors - and the default lets it through
                // without a word. asserted-only fails the build unless the equivalence was written
                // down deliberately. --exclude-tautologies structural drops the inferences that are
                // true of any ontology and only pad the output. Real ODK passes both, in reason_test.
                + "reason:\n"
                + "\t$(ROBOT) reason -r ELK -i $(ONT)-edit.owl \\\n"
                + "\t  --equivalent-classes-allowed asserted-only \\\n"
                + "\t  --exclude-tautologies structural \\\n"
                + "\t  -o $(ONT).owl\n\n"
                // --fail-on and --labels are passed because the YAML above declares them.
                // They were declared and not passed, so CI did whatever ROBOT defaults to rather
                // than what the project said - and a build that says fail_on: ERROR while not
                // failing on errors is worse than one that says nothing.
                // profile.txt holds every rule ROBOT knows, at ROBOT's own severity, and it must
                // stay free of comment lines - ROBOT's parser reads every line as a level and a
                // rule. Said here because this is a Makefile, where # is a comment, and profile.txt
                // is the one place it cannot be said.
                + "# profile.txt lists every ROBOT report rule at its severity. ROBOT does NOT\n"
                + "# merge it with its defaults - it runs exactly what is in the file, so a rule\n"
                + "# you delete stops running silently. To relax one, change ERROR to WARN or INFO\n"
                + "# rather than deleting the line. Do not put comments in profile.txt: ROBOT has\n"
                + "# no comment syntax there and will refuse to run.\n"
                + "report:\n"
                + "\t$(ROBOT) report -i $(ONT)-edit.owl --profile profile.txt \\\n"
                + "\t  --fail-on ERROR --labels true \\\n"
                + "\t  --output report.tsv --format tsv\n\n"
                // robot verify exits non-zero when a query returns rows, which is what makes a
                // SPARQL file a check rather than a decoration.
                + "sparql_test:\n"
                + "\t$(ROBOT) verify --input $(ONT)-edit.owl --queries ../sparql/*.rq --output-dir .\n\n"
                // Real ODK validates the OWL 2 DL profile as part of its own `test` target and this
                // scaffold did not, so an ontology could drift out of DL with CI staying green.
                // Outside DL means the guarantees every OWL reasoner relies on no longer hold: a
                // reasoner may give a different answer, or none, and nothing would have said so.
                //
                // merge then convert first, as ODK does. The merge folds in the imports closure -
                // a violation can be created by the combination rather than by either side - and
                // the functional-syntax round trip normalises what the RDF/XML parser would
                // otherwise leave implicit, so the check answers for the artefact rather than for
                // one serialisation of it.
                //
                // `|| { cat ... ; exit 1; }` because robot writes the reasons into the output file
                // and a bare non-zero exit tells a user only that something is wrong.
                + "validate_profile:\n"
                + "\t$(ROBOT) merge -i $(ONT)-edit.owl convert -f ofn -o tmp_validate.ofn\n"
                + "\t$(ROBOT) validate-profile --profile DL -i tmp_validate.ofn \\\n"
                + "\t  -o validate-profile.txt || { cat validate-profile.txt; exit 1; }\n"
                + "\t@rm -f tmp_validate.ofn\n\n"
                + "clean:\n"
                + "\t@rm -f tmp_* report.tsv validate-profile.txt *.bak *.csv $(ONT).owl\n\n"
                // test, not "reason report". prepare_release used to run a weaker gate than
                // `make test` did: it left out sparql_test, so a release could be cut while one of
                // the project's own SPARQL checks was failing. A release gate that is weaker than
                // the CI gate is the wrong way round - the release is the artefact people cite.
                + "prepare_release: test\n"
                // Dated and stamped, not copied. A release with no owl:versionIRI cannot be
                // cited or pinned by anyone downstream, and an undated copy means each release
                // destroys the last - which is what the previous single cp did.
                + "\t@mkdir -p ../../releases/$(TODAY)\n"
                + "\t$(ROBOT) annotate --input $(ONT).owl \\\n"
                // ProjectIri.stemOf, not the raw base IRI: a base ending in .owl - which is
                // what the wizard defaults to - produced .../obo/mwo.owl/releases/<date>/mwo.owl,
                // a third spelling of the same release. The ID-ranges IRI below already stripped
                // the extension, so the generator disagreed with itself in one file.
                + "\t  --version-iri \"" + ProjectIri.stemOf(c.getBaseIri())
                + "/releases/$(TODAY)/$(ONT).owl\" \\\n"
                + "\t  --annotation owl:versionInfo \"$(TODAY)\" \\\n"
                + "\t  --output ../../releases/$(TODAY)/$(ONT).owl\n"
                + "\t@cp ../../releases/$(TODAY)/$(ONT).owl ../../$(ONT).owl\n";
    }

    private static String customMakefile(OdkProjectConfig c) {
        return "# Custom targets for " + c.getOntologyId() + ".\n"
                + "# This file is never overwritten - put your own rules here.\n";
    }

    /**
     * The ID ranges file, in the shape ODK actually uses.
     *
     * <p>What was here before was wrong rather than merely incomplete: it asserted an
     * invented {@code idrange:has_id_policy} property under the project's own namespace, and
     * declared no IRI prefix, no digit count and no ranges at all. ODK's tooling does not
     * recognise that property, and a project generated from it could not allocate identifiers
     * to anybody - so two collaborators would mint the same identifier by construction. The
     * real format and its four OBO properties are in {@link IdRanges}; the reference file is
     * {@code ISE-FIZKarlsruhe/mwo/src/ontology/mwo-idranges.owl}.
     *
     * <p>One range is allocated up front, to whoever is creating the project. A file with no
     * ranges is what the previous version effectively produced, and it makes the very first
     * minting attempt fail for the one person guaranteed to be there.
     */
    private static String idRanges(OdkProjectConfig c) {
        String id = c.getOntologyId();
        String upper = id.toUpperCase(java.util.Locale.ROOT);
        String base = c.getBaseIri().replaceAll("\\.owl$", "");
        return IdRanges.create(base + "/" + id + "-idranges.owl", upper,
                        IdRanges.prefixFor(c.getBaseIri(), id), 7)
                .withRange(firstEditor(), 1000, 9999)
                .toManchester();
    }

    /**
     * Who the first ID range belongs to.
     *
     * <p>The OS account name: there is nothing better available while scaffolding, and it is at
     * least stable and recognisable to the person it names. They can rename it in the file. What
     * matters is that a range exists at all, so the project can mint from the moment it is
     * created.
     */
    private static String firstEditor() {
        String name = System.getProperty("user.name", "");
        return name.trim().isEmpty() ? "FirstEditor" : name.trim();
    }

    /**
     * Pins line endings, so the project is the same bytes on every machine.
     *
     * <p>Git is commonly configured with {@code core.autocrlf=true}, which rewrites text files to
     * CRLF on checkout while storing LF. Everything this scaffold writes is LF, so without this a
     * Windows clone has CRLF in the working tree and any byte comparison against freshly generated
     * content fails - including the one <em>Project &gt; Update project files...</em> makes, which
     * would then report every generated file as changed on that machine and nowhere else.
     *
     * <p>{@code eol=lf} rather than {@code text=auto}: ROBOT, make and the OWL files are all
     * happier with LF on every platform, and "the same everywhere" is worth more here than matching
     * a local convention.
     */
    private static String gitattributes() {
        return "# Line endings are pinned so this project is the same bytes on every machine.\n"
                + "#\n"
                + "# Git is often configured with core.autocrlf=true, which rewrites text files to\n"
                + "# CRLF on checkout. Everything OntoBoard generates is LF, so without this a\n"
                + "# Windows clone gets CRLF in the working tree - and then any byte comparison\n"
                + "# against regenerated content differs on that machine and nowhere else.\n"
                + "* text=auto eol=lf\n"
                + "\n"
                + "# Not text: these are binary or effectively so.\n"
                + "*.png binary\n"
                + "*.jpg binary\n"
                + "*.zip binary\n";
    }

    private static String catalog() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
                + "<catalog prefer=\"public\" xmlns=\"urn:oasis:names:tc:entity:xmlns:xml:catalog\">\n"
                + "    <!-- Map import IRIs to local files in imports/ as you add them.\n"
                + "         ROBOT > Import terms... adds an entry here for every module it saves,\n"
                // No double hyphen anywhere in here: "--" is illegal inside an XML comment, and a
                // catalog that does not parse fails every robot call in the generated build. An
                // earlier wording of this comment named the catalog command-line flag literally and
                // broke `make` outright - found by running the scaffolded project, not by reading it.
                + "         and the Makefile hands this file to robot with its catalog option, so\n"
                + "         those imports resolve from disk with no network. -->\n"
                + "</catalog>\n";
    }

    /**
     * The ROBOT report profile: every rule ROBOT knows, at ROBOT's own severity.
     *
     * <p>This used to list seven rules, and that was not a smaller profile - it was a silently
     * emptier one. {@code ReportOperation.getProfile(path)} builds a fresh map from the file and
     * does not merge it with ROBOT's defaults (the bundled {@code report_profile.txt} is read only
     * when no path is given), so a project shipping seven lines ran seven of thirty-two checks.
     * Both this plugin's own quality report and the generated CI read the same file, so both were
     * equally blind, and nothing anywhere said which rules were not running.
     *
     * <p>The rules that were off by omission are the ones that catch exactly the damage several
     * editors do to one ontology: {@code deprecated_class_reference},
     * {@code misused_obsolete_label}, {@code misused_replaced_by}, {@code duplicate_label},
     * {@code duplicate_definition}, {@code illegal_use_of_built_in_vocabulary},
     * {@code multiple_equivalent_class_definitions}, {@code invalid_entity_uri}. Two more were
     * quietly downgraded - {@code missing_label} from ERROR to WARN and {@code multiple_labels}
     * from ERROR to INFO.
     *
     * <p>So: every rule, at ROBOT's level, written out in full. A project that wants a rule
     * relaxed edits this file and can see what it changed; nobody loses a check by never having
     * been told it existed. Kept in step with robot-core by a test that reads ROBOT's own bundled
     * profile, so upgrading the dependency fails the build rather than silently adding a rule
     * nobody runs.
     */
    private static String reportProfile() {
        // NO COMMENTS. ROBOT's profile parser reads every line as "<LEVEL> <rule>" and has no
        // comment syntax, so a leading # is parsed as a reporting level and the run dies with
        // "REPORT LEVEL ERROR '# ...' is not a valid reporting level". An explanatory header here
        // broke `make report` in every project this scaffold produced - proven by running ODK
        // against a generated project rather than by reading the documentation, which does not
        // say so either way. The explanation lives in the Makefile and the README instead, where
        // # is a comment and a person will actually meet it.
        return "WARN\tannotation_whitespace\n"
                + "ERROR\tdeprecated_boolean_datatype\n"
                + "ERROR\tdeprecated_class_reference\n"
                + "ERROR\tdeprecated_property_reference\n"
                + "ERROR\tduplicate_definition\n"
                + "WARN\tduplicate_exact_synonym\n"
                + "WARN\tduplicate_label_synonym\n"
                + "ERROR\tduplicate_label\n"
                + "WARN\tduplicate_scoped_synonym\n"
                + "WARN\tequivalent_pair\n"
                + "WARN\tequivalent_class_axiom_no_genus\n"
                + "ERROR\tillegal_use_of_built_in_vocabulary\n"
                + "WARN\tinvalid_xref\n"
                + "ERROR\tlabel_formatting\n"
                + "ERROR\tlabel_whitespace\n"
                + "INFO\tlowercase_definition\n"
                + "WARN\tmissing_definition\n"
                + "ERROR\tmissing_label\n"
                + "WARN\tmissing_obsolete_label\n"
                + "ERROR\tmissing_ontology_description\n"
                + "ERROR\tmissing_ontology_license\n"
                + "ERROR\tmissing_ontology_title\n"
                + "WARN\tmissing_subset_declaration\n"
                + "INFO\tmissing_superclass\n"
                + "WARN\tmissing_synonymtype_declaration\n"
                + "ERROR\tmisused_obsolete_label\n"
                + "ERROR\tmisused_replaced_by\n"
                + "ERROR\tmultiple_definitions\n"
                + "WARN\tmultiple_equivalent_classes\n"
                + "ERROR\tmultiple_equivalent_class_definitions\n"
                + "ERROR\tmultiple_labels\n"
                + "WARN\tinvalid_entity_uri\n";
    }

    private static String checkLabels() {
        return "# Every class should carry an rdfs:label.\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX owl: <http://www.w3.org/2002/07/owl#>\n"
                + "SELECT ?entity WHERE {\n"
                + "  ?entity a owl:Class .\n"
                + "  FILTER NOT EXISTS { ?entity rdfs:label ?label }\n"
                + "  FILTER (!isBlank(?entity))\n"
                + "}\n";
    }

    private static String workflow(OdkProjectConfig c, String robotVersion) {
        return "name: QC\n\n"
                + "on:\n"
                + "  push:\n"
                + "  pull_request:\n\n"
                + "jobs:\n"
                + "  build:\n"
                + "    runs-on: ubuntu-latest\n"
                + "    steps:\n"
                + "      - uses: actions/checkout@v4\n"
                // Pinned, and allowed to fail. "latest" meant CI could move to a ROBOT that
                // reports differently from the one OntoBoard embeds, without anybody deciding to.
                // And without --fail, curl exits 0 on a missing asset and writes the nine bytes
                // "Not Found" into robot.jar - so the step named "Install ROBOT" went green and
                // the failure surfaced later as a corrupt-jar error pointing at the ontology.
                + "      - name: Install ROBOT\n"
                + "        run: |\n"
                + "          curl -fsSL --retry 3 -o robot.jar \\\n"
                + "            https://github.com/ontodev/robot/releases/download/v"
                + robotVersion + "/robot.jar\n"
                + "          printf '#!/bin/sh\\nexec java -jar %s/robot.jar \"$@\"\\n' "
                + "\"$PWD\" | sudo tee /usr/local/bin/robot > /dev/null\n"
                + "          sudo chmod +x /usr/local/bin/robot\n"
                + "          robot --version\n"
                + "      - name: Run QC\n"
                + "        working-directory: src/ontology\n"
                + "        run: make test\n"
                // The job summary says how many violations there were; only report.tsv says
                // which. Uploading it is the difference between "QC failed, 3 errors" and knowing
                // what to fix without reproducing the run on your own machine.
                + "      - name: Upload the report\n"
                + "        if: always()\n"
                + "        uses: actions/upload-artifact@v4\n"
                + "        with:\n"
                + "          name: robot-report\n"
                + "          path: src/ontology/report.tsv\n"
                + "          if-no-files-found: ignore\n";
    }

    /**
     * What not to commit: generated output, and nothing else.
     *
     * <p>{@code src/ontology/imports/*.owl} used to be here and it was actively harmful. An import
     * module is not generated output that anyone can reproduce - it is a few dozen axioms this
     * project chose to copy out of a much larger ontology at a particular release, and ODK
     * projects commit them. Ignoring them while committing the catalog entry and the import
     * declaration that point at them produces a repository whose imports resolve for the person
     * who made them and for nobody else: clone it, and the catalog maps an IRI to a file that is
     * not there.
     *
     * <p>That is exactly the failure {@code ImportTermsAction} writes a catalog entry to prevent,
     * reintroduced one directory away. CI would not catch it either - the generated workflow runs
     * {@code make test}, which reports on the edit file without loading its imports.
     */
    private static String gitignore(OdkProjectConfig c) {
        return "# Build products only.\n"
                + "#\n"
                + "# The release artefact - <id>.owl at the project ROOT, written by\n"
                + "# `make prepare_release` - is deliberately not here. That one is the\n"
                + "# product, and ODK projects commit it so a PURL resolves to something.\n"
                + "#\n"
                + "# Import modules under src/ontology/imports/ are not here either. A\n"
                + "# module is not reproducible output: it is a few dozen axioms this\n"
                + "# project chose to copy from a much larger ontology at a particular\n"
                + "# release. Ignore it and the catalog entry beside it points at a file\n"
                + "# nobody else has.\n"
                + "#\n"
                + "# src/ontology/mirror/ IS ignored, unlike imports/. A mirror is a\n"
                + "# downloaded copy of an upstream ontology - CHEBI alone is hundreds of\n"
                + "# megabytes - and it is reproducible from the source each term list\n"
                + "# records. Project > Refresh imports... rebuilds it. The modules under\n"
                + "# imports/ are NOT reproducible that way, which is why those are\n"
                + "# committed and this is not.\n"
                + "src/ontology/mirror/\n"
                + "tmp_*\n"
                + "report.tsv\n"
                // validate_profile writes this. It was added to `clean` and not here, so a
                // project would have committed its own build output.
                + "validate-profile.txt\n"
                + "# robot verify writes one CSV per failing query into src/ontology.\n"
                + "src/ontology/*.csv\n"
                + "*.bak\n"
                + "src/ontology/" + c.getOntologyId() + ".owl\n";
    }

    private static String readme(OdkProjectConfig c) {
        String id = c.getOntologyId();
        return "# " + c.getTitle() + "\n\n"
                + c.getDescription() + "\n\n"
                + "IRI: `" + c.getBaseIri() + "`\n\n"
                + "## Editing\n\n"
                + "Open `src/ontology/" + id + "-edit.owl` in Protege. That is the file you\n"
                + "edit; `" + id + ".owl` is generated by the build.\n\n"
                + "## Building\n\n"
                + "From `src/ontology`, with `make` and ROBOT on your PATH:\n\n"
                + "```\n"
                // All seven, not three. The build had a default goal and a release target that the
                // README never mentioned, so the two commands a maintainer most needs - the bare
                // `make`, and the one that cuts a release - were the two they had to find by
                // reading the Makefile they are told not to edit.
                + "make all        # reason, then report - and what a bare `make` runs\n"
                + "make reason     # classify with ELK into " + id + ".owl\n"
                + "make report     # ROBOT quality report -> report.tsv\n"
                + "make sparql_test  # run every check in ../sparql over the edit file\n"
                + "make validate_profile  # fail if the ontology has left OWL 2 DL\n"
                + "make test       # what CI runs: reason, report and sparql_test\n"
                + "make prepare_release  # test, then a dated, version-stamped release\n"
                + "make clean      # delete the generated files\n"
                + "```\n\n"
                + "Custom targets go in `" + id + ".Makefile`, which the build includes and\n"
                + "never overwrites. `Makefile` itself is generated - do not edit it.\n\n"
                + "Generated by OntoBoard.\n";
    }

    private static String uriBase(OdkProjectConfig c) {
        String base = c.getBaseIri();
        int lastSlash = base.lastIndexOf('/');
        return lastSlash > 0 ? base.substring(0, lastSlash) : base;
    }

    private static void mkdirs(File dir) {
        if (!dir.exists() && !dir.mkdirs()) {
            throw new UncheckedIOException(
                    new IOException("Could not create " + dir.getAbsolutePath()));
        }
    }

    private static File write(File target, String content) {
        try {
            Files.write(target.toPath(), content.getBytes(UTF8));
            return target;
        } catch (IOException failure) {
            throw new UncheckedIOException(
                    "Could not write " + target.getAbsolutePath(), failure);
        }
    }

    private static String xml(String value) {
        return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
