package de.fizkarlsruhe.ise.ontoboard.odk;

import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;

/**
 * Generates an ODK-compatible repository without Docker.
 *
 * <p>The real Ontology Development Kit seeds a repo by running its own image, which means
 * installing Docker before writing a single axiom. That barrier is one of the two the
 * project set out to remove, so the layout is written directly here - the same approach the
 * retired web application took, and the same file tree, so a project generated by either is
 * interchangeable.
 *
 * <p>What is generated is a real ODK workspace: {@code src/ontology} with the edit file,
 * ODK YAML, Makefile pair, catalog, ID ranges and ROBOT report profile, plus SPARQL quality
 * checks, a GitHub Actions workflow and a README. It does not need Docker to be *created*;
 * running its Makefile targets still needs {@code make} and ROBOT on PATH.
 */
public final class OdkScaffold {

    private static final Charset UTF8 = Charset.forName("UTF-8");

    private OdkScaffold() {
    }

    /**
     * Creates the project.
     *
     * @return every file written, in creation order, so the caller can report what happened
     * @throws IllegalArgumentException if the config is invalid or the target already exists
     */
    public static List<File> create(OdkProjectConfig config) {
        config.validate();

        File root = config.getProjectRoot();
        File src = new File(root, "src");
        File ontology = new File(src, "ontology");

        mkdirs(ontology);
        mkdirs(new File(ontology, "imports"));
        mkdirs(new File(src, "metadata"));
        mkdirs(new File(src, "scripts"));
        mkdirs(new File(src, "sparql"));
        mkdirs(new File(src, "patterns"));
        mkdirs(new File(root, "docs"));
        mkdirs(new File(new File(root, ".github"), "workflows"));

        String id = config.getOntologyId();
        List<File> written = new ArrayList<File>();

        // The edit file is what Protege opens; the release file starts as a copy.
        String editOwl = editOwl(config);
        written.add(write(new File(ontology, id + "-edit.owl"), editOwl));
        written.add(write(new File(ontology, id + ".owl"), editOwl));

        written.add(write(new File(ontology, id + "-odk.yaml"), odkYaml(config)));
        written.add(write(new File(ontology, "Makefile"), generatedMakefile(config)));
        written.add(write(new File(ontology, id + ".Makefile"), customMakefile(config)));
        written.add(write(new File(ontology, id + "-idranges.owl"), idRanges(config)));
        written.add(write(new File(ontology, "catalog-v001.xml"), catalog()));
        written.add(write(new File(ontology, "profile.txt"), reportProfile()));
        written.add(write(new File(new File(src, "sparql"), "check_labels.rq"), checkLabels()));
        written.add(write(new File(new File(new File(root, ".github"), "workflows"), "qc.yml"),
                workflow(config)));
        written.add(write(new File(root, ".gitignore"), gitignore()));
        written.add(write(new File(root, "README.md"), readme(config)));
        return written;
    }

    private static String editOwl(OdkProjectConfig c) {
        return "<?xml version=\"1.0\"?>\n"
                + "<rdf:RDF xmlns=\"" + c.getNamespace() + "\"\n"
                + "     xml:base=\"" + c.getBaseIri() + "\"\n"
                + "     xmlns:owl=\"http://www.w3.org/2002/07/owl#\"\n"
                + "     xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n"
                + "     xmlns:rdfs=\"http://www.w3.org/2000/01/rdf-schema#\"\n"
                + "     xmlns:xsd=\"http://www.w3.org/2001/XMLSchema#\"\n"
                + "     xmlns:dcterms=\"http://purl.org/dc/terms/\">\n"
                + "    <owl:Ontology rdf:about=\"" + c.getBaseIri() + "\">\n"
                + "        <rdfs:label xml:lang=\"en\">" + xml(c.getTitle()) + "</rdfs:label>\n"
                + "        <dcterms:title xml:lang=\"en\">" + xml(c.getTitle()) + "</dcterms:title>\n"
                + "        <dcterms:description xml:lang=\"en\">"
                + xml(c.getDescription()) + "</dcterms:description>\n"
                + (c.getLicense().isEmpty() ? ""
                        : "        <dcterms:license rdf:resource=\"" + xml(c.getLicense())
                                + "\"/>\n")
                + "        <owl:versionInfo>0.1.0</owl:versionInfo>\n"
                + "    </owl:Ontology>\n"
                + "</rdf:RDF>\n";
    }

    private static String odkYaml(OdkProjectConfig c) {
        return "# ODK configuration for " + c.getTitle() + "\n"
                // Not "sh run.sh make update_repo". That is ODK's own instruction and it
                // names a 150-line Docker wrapper around obolibrary/odkfull - which this scaffold
                // deliberately does not write, because running the pipeline without a Docker
                // prerequisite is the reason this plugin embeds robot-core. Telling a user to run
                // a file that does not exist is worse than telling them nothing.
                + "# This project's Makefile calls robot directly, so it needs make and robot on\n"
                + "# PATH - not Docker. Edit the Makefile by hand; nothing regenerates it.\n"
                + "id: " + c.getOntologyId() + "\n"
                + "title: \"" + c.getTitle() + "\"\n"
                + "description: \"" + c.getDescription() + "\"\n"
                + "uribase: " + uriBase(c) + "\n"
                + (c.getLicense().isEmpty() ? "" : "license: " + c.getLicense() + "\n")
                + "release_artefacts:\n"
                + "  - base\n"
                + "  - full\n"
                + "primary_release: full\n"
                + "export_formats:\n"
                + "  - owl\n"
                + "  - obo\n"
                + "  - json\n"
                + "import_group:\n"
                + "  products: []\n"
                + "robot_report:\n"
                + "  use_labels: TRUE\n"
                + "  fail_on: ERROR\n"
                + "  report_on:\n"
                + "    - edit\n";
    }

    private static String generatedMakefile(OdkProjectConfig c) {
        String id = c.getOntologyId();
        return "# WARNING: generated by OntoBoard. Do NOT edit by hand.\n"
                + "# Put custom targets in " + id + ".Makefile, which is included below.\n\n"
                + "ONT_ID := " + id + "\n"
                + "ONT := $(ONT_ID)\n"
                + "TODAY := $(shell date +%Y-%m-%d)\n\n"
                + "-include $(ONT).Makefile\n\n"
                + ".PHONY: all test reason report clean prepare_release\n\n"
                + "all: reason report\n"
                + "\t@echo \"Build complete: $(ONT)\"\n\n"
                + "test: report\n\n"
                + "reason:\n"
                + "\trobot reason -r ELK -i $(ONT)-edit.owl -o $(ONT).owl\n\n"
                + "report:\n"
                + "\trobot report -i $(ONT)-edit.owl --profile profile.txt "
                + "--output report.tsv --format tsv\n\n"
                + "clean:\n"
                + "\t@rm -f tmp_* report.tsv *.bak $(ONT).owl\n\n"
                + "prepare_release: reason report\n"
                // Dated and stamped, not copied. A release with no owl:versionIRI cannot be
                // cited or pinned by anyone downstream, and an undated copy means each release
                // destroys the last - which is what the previous single cp did.
                + "\t@mkdir -p ../../releases/$(TODAY)\n"
                + "\trobot annotate --input $(ONT).owl \\\n"
                + "\t  --version-iri \"" + c.getBaseIri() + "/releases/$(TODAY)/$(ONT).owl\" \\\n"
                + "\t  --annotation owl:versionInfo \"$(TODAY)\" \\\n"
                + "\t  --output ../../releases/$(TODAY)/$(ONT).owl\n"
                + "\t@cp ../../releases/$(TODAY)/$(ONT).owl ../../$(ONT).owl\n";
    }

    private static String customMakefile(OdkProjectConfig c) {
        return "# Custom targets for " + c.getOntologyId() + ".\n"
                + "# This file is never overwritten - put your own rules here.\n";
    }

    /**
     * The ID ranges file, in the shape ODK actually uses.
     *
     * <p>What was here before was wrong rather than merely incomplete: it asserted an
     * invented {@code idrange:has_id_policy} property under the project's own namespace, and
     * declared no IRI prefix, no digit count and no ranges at all. ODK's tooling does not
     * recognise that property, and a project generated from it could not allocate identifiers
     * to anybody - so two collaborators would mint the same identifier by construction. The
     * real format and its four OBO properties are in {@link IdRanges}; the reference file is
     * {@code ISE-FIZKarlsruhe/mwo/src/ontology/mwo-idranges.owl}.
     *
     * <p>One range is allocated up front, to whoever is creating the project. A file with no
     * ranges is what the previous version effectively produced, and it makes the very first
     * minting attempt fail for the one person guaranteed to be there.
     */
    private static String idRanges(OdkProjectConfig c) {
        String id = c.getOntologyId();
        String upper = id.toUpperCase(java.util.Locale.ROOT);
        String base = c.getBaseIri().replaceAll("\\.owl$", "");
        return IdRanges.create(base + "/" + id + "-idranges.owl", upper,
                        IdRanges.prefixFor(c.getBaseIri(), id), 7)
                .withRange(firstEditor(), 1000, 9999)
                .toManchester();
    }

    /**
     * Who the first ID range belongs to.
     *
     * <p>The OS account name: there is nothing better available while scaffolding, and it is at
     * least stable and recognisable to the person it names. They can rename it in the file. What
     * matters is that a range exists at all, so the project can mint from the moment it is
     * created.
     */
    private static String firstEditor() {
        String name = System.getProperty("user.name", "");
        return name.trim().isEmpty() ? "FirstEditor" : name.trim();
    }

    private static String catalog() {
        return "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n"
                + "<catalog prefer=\"public\" xmlns=\"urn:oasis:names:tc:entity:xmlns:xml:catalog\">\n"
                + "    <!-- Map import IRIs to local files in imports/ as you add them. -->\n"
                + "</catalog>\n";
    }

    private static String reportProfile() {
        return "ERROR\tmissing_ontology_license\n"
                + "ERROR\tmissing_ontology_title\n"
                + "ERROR\tmissing_ontology_description\n"
                + "ERROR\tinvalid_xref\n"
                + "WARN\tmissing_definition\n"
                + "WARN\tmissing_label\n"
                + "INFO\tmultiple_labels\n";
    }

    private static String checkLabels() {
        return "# Every class should carry an rdfs:label.\n"
                + "PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>\n"
                + "PREFIX owl: <http://www.w3.org/2002/07/owl#>\n"
                + "SELECT ?entity WHERE {\n"
                + "  ?entity a owl:Class .\n"
                + "  FILTER NOT EXISTS { ?entity rdfs:label ?label }\n"
                + "  FILTER (!isBlank(?entity))\n"
                + "}\n";
    }

    private static String workflow(OdkProjectConfig c) {
        return "name: QC\n\n"
                + "on:\n"
                + "  push:\n"
                + "  pull_request:\n\n"
                + "jobs:\n"
                + "  build:\n"
                + "    runs-on: ubuntu-latest\n"
                + "    steps:\n"
                + "      - uses: actions/checkout@v4\n"
                + "      - name: Install ROBOT\n"
                + "        run: |\n"
                + "          curl -L -o robot.jar https://github.com/ontodev/robot/releases/"
                + "latest/download/robot.jar\n"
                + "          echo 'java -jar '\"$PWD\"'/robot.jar \"$@\"' > /usr/local/bin/robot\n"
                + "          chmod +x /usr/local/bin/robot\n"
                + "      - name: Run QC\n"
                + "        working-directory: src/ontology\n"
                + "        run: make test\n";
    }

    /**
     * Build products and scratch files only.
     *
     * <p>Note what is deliberately NOT here: {@code *.ontoboard.json}. An earlier version
     * ignored the canvas sidecar, which meant two people cloning the repository each got an
     * empty board and neither could see the other's diagram at all. The file exists precisely
     * so a diagram can be shared without touching the ontology, and ignoring it removed the
     * only way to share it. It is small, stable and diffs cleanly. A team that would rather
     * keep diagrams private can add the line back; a team that never thinks about it gets the
     * better default.
     */
    private static String gitignore() {
        return "tmp_*\nreport.tsv\n*.bak\nsrc/ontology/imports/*.owl\n";
    }

    private static String readme(OdkProjectConfig c) {
        String id = c.getOntologyId();
        return "# " + c.getTitle() + "\n\n"
                + c.getDescription() + "\n\n"
                + "IRI: `" + c.getBaseIri() + "`\n\n"
                + "## Editing\n\n"
                + "Open `src/ontology/" + id + "-edit.owl` in Protege. That is the file you\n"
                + "edit; `" + id + ".owl` is generated by the build.\n\n"
                + "## Building\n\n"
                + "From `src/ontology`, with `make` and ROBOT on your PATH:\n\n"
                + "```\n"
                + "make reason   # classify with ELK into " + id + ".owl\n"
                + "make report   # ROBOT quality report -> report.tsv\n"
                + "make test     # what CI runs\n"
                + "```\n\n"
                + "Custom targets go in `" + id + ".Makefile`, which the build includes and\n"
                + "never overwrites. `Makefile` itself is generated - do not edit it.\n\n"
                + "Generated by OntoBoard.\n";
    }

    private static String uriBase(OdkProjectConfig c) {
        String base = c.getBaseIri();
        int lastSlash = base.lastIndexOf('/');
        return lastSlash > 0 ? base.substring(0, lastSlash) : base;
    }

    private static void mkdirs(File dir) {
        if (!dir.exists() && !dir.mkdirs()) {
            throw new UncheckedIOException(
                    new IOException("Could not create " + dir.getAbsolutePath()));
        }
    }

    private static File write(File target, String content) {
        try {
            Files.write(target.toPath(), content.getBytes(UTF8));
            return target;
        } catch (IOException failure) {
            throw new UncheckedIOException(
                    "Could not write " + target.getAbsolutePath(), failure);
        }
    }

    private static String xml(String value) {
        return value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
