package de.fizkarlsruhe.ise.ontoboard.canvas;

import de.fizkarlsruhe.ise.ontoboard.model.CanvasEdge;
import de.fizkarlsruhe.ise.ontoboard.model.CanvasNode;
import de.fizkarlsruhe.ise.ontoboard.model.Projection;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * The board as a GraphViz DOT graph.
 *
 * <p>Taken from OntoGraf, which has an {@code ExportAsDotAction}. PNG and SVG hand somebody a
 * picture; DOT hands them the graph, so a house style, a LaTeX pipeline or a different layout
 * engine can render it their way. For a paper that is frequently the only acceptable answer -
 * the figure has to match the rest of the document, and an exported bitmap never will.
 *
 * <p>Text, deliberately: no GraphViz is bundled and none is needed, because the output is the
 * input to somebody else's tool. {@code dot -Tpdf board.dot -o board.pdf}.
 *
 * <p>The styling mirrors the canvas rather than reproducing it. DOT has no concept of a
 * namespace outline colour or a note badge, and faking them with approximations would produce a
 * picture that looks like the board and disagrees with it in detail. What carries across is what
 * DOT expresses natively: the shape of a node, the style of an edge, and the labels.
 */
public final class DotExport {

    private DotExport() {
    }

    /**
     * The projection as DOT source.
     *
     * <p>Identifiers are sequential ({@code n0}, {@code n1}) with the IRI kept as a {@code tooltip}
     * attribute. DOT identifiers may not contain most of what an IRI contains, and quoting around
     * the problem produces a file that half of the tooling rejects - so the IRI travels as data
     * where it is safe, and every renderer agrees about the identifiers.
     */
    public static String of(Projection projection, String title) {
        StringBuilder dot = new StringBuilder();
        dot.append("// Generated by OntoBoard. Render with:  dot -Tpdf board.dot -o board.pdf\n");
        dot.append("digraph ").append(quote(title == null || title.trim().isEmpty()
                ? "board" : title.trim())).append(" {\n");
        dot.append("  rankdir=BT;\n");
        dot.append("  graph [fontname=\"Helvetica\", splines=true];\n");
        dot.append("  node  [fontname=\"Helvetica\", fontsize=10, style=filled, "
                + "fillcolor=\"#FFFFFF\"];\n");
        dot.append("  edge  [fontname=\"Helvetica\", fontsize=9];\n\n");

        if (projection == null) {
            return dot.append("}\n").toString();
        }

        Map<String, String> names = new LinkedHashMap<String, String>();
        int next = 0;
        for (CanvasNode node : projection.getNodes()) {
            String name = "n" + next++;
            names.put(node.getId(), name);
            dot.append("  ").append(name)
                    .append(" [label=").append(quote(labelOf(node)))
                    .append(", shape=").append(shapeOf(node))
                    .append(", tooltip=").append(quote(node.getId()));
            if (node.isUnsatisfiable()) {
                // The one node state DOT can carry honestly: a reasoner said this can have no
                // instances, which is a different claim from "drawn in red".
                dot.append(", color=\"#C62828\", penwidth=2");
            } else if (node.isImported()) {
                dot.append(", color=\"#9CA3AF\", fontcolor=\"#5A6470\"");
            }
            dot.append("];\n");
        }

        dot.append('\n');
        for (CanvasEdge edge : projection.getEdges()) {
            String from = names.get(edge.getSourceId());
            String to = names.get(edge.getTargetId());
            if (from == null || to == null) {
                // An edge to something not on the board cannot be drawn and must not invent a
                // node to point at - the same opt-in rule the canvas itself holds to.
                continue;
            }
            dot.append("  ").append(from).append(" -> ").append(to).append(" [");
            dot.append(styleOf(edge));
            if (edge.getLabel() != null && !edge.getLabel().trim().isEmpty()) {
                dot.append(", label=").append(quote(edge.getLabel()));
            }
            dot.append("];\n");
        }
        return dot.append("}\n").toString();
    }

    /** A node's two lines, as DOT writes a line break. */
    private static String labelOf(CanvasNode node) {
        String identifier = node.getCurie();
        String label = node.getLabel() == null ? "" : node.getLabel();
        if (identifier == null || identifier.isEmpty() || identifier.equals(label)) {
            return label;
        }
        return identifier + "\n" + label;
    }

    private static String shapeOf(CanvasNode node) {
        switch (node.getKind()) {
            case INDIVIDUAL:
                return "diamond";
            case DATATYPE:
                return "ellipse";
            case LITERAL:
                return "note";
            case OBJECT_PROPERTY:
            case DATA_PROPERTY:
                return "hexagon";
            case CLASS:
            default:
                return "box";
        }
    }

    /**
     * How an edge is drawn.
     *
     * <p>A subclass arrow keeps UML's hollow triangle, which is what an ontology reader expects
     * for is-a; an inferred one is dotted and grey, as it is on the board, so a reader cannot
     * mistake a reasoner's conclusion for an axiom in the file.
     */
    private static String styleOf(CanvasEdge edge) {
        switch (edge.getKind()) {
            case SUBCLASS:
                return "arrowhead=empty";
            case INFERRED_SUBCLASS:
                return "arrowhead=empty, style=dotted, color=\"#9CA3AF\"";
            case INFERRED_TYPE:
                return "style=dotted, color=\"#9CA3AF\"";
            case TYPE:
                return "style=dashed";
            case SUB_PROPERTY:
                return "arrowhead=empty, color=\"#B45309\"";
            case DATA_PROPERTY:
                return "color=\"#0F766E\"";
            case OBJECT_PROPERTY:
            default:
                return "color=\"#1D4ED8\"";
        }
    }

    /**
     * A DOT string literal.
     *
     * <p>Backslashes first, or escaping the quotes would then escape the escapes. A real newline
     * becomes {@code \\n}, which is how DOT writes a line break inside a label.
     */
    static String quote(String value) {
        if (value == null) {
            return "\"\"";
        }
        String escaped = value
                .replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\r", "")
                .replace("\n", "\\n");
        return "\"" + escaped + "\"";
    }
}
