package de.fizkarlsruhe.ise.ontoboard.menu;

import de.fizkarlsruhe.ise.ontoboard.git.GitClone;
import de.fizkarlsruhe.ise.ontoboard.git.GitHubUrl;
import de.fizkarlsruhe.ise.ontoboard.git.RepoLayout;
import de.fizkarlsruhe.ise.ontoboard.odk.ImportHealth;
import de.fizkarlsruhe.ise.ontoboard.odk.OdkProjectLoader;
import java.io.File;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;
import javax.swing.SwingUtilities;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * Project &gt; Open from GitHub - clone an ontology repository and open the right file in it.
 *
 * <p>Two things about it are the point, and both are things a user gets wrong on their own.
 *
 * <p>The first is that it clones with <b>git</b> rather than downloading a zip. An ODK repository
 * is not a snapshot to look at; it is a working copy someone will branch, commit and push from,
 * and it has to be the same working copy their shell and their CI see, with their credential
 * helper and their config. A downloaded zip looks identical and cannot be pushed.
 *
 * <p>The second is that it opens the <b>edit file</b>. An ODK repository holds a dozen ontology
 * files, of which one is the source of truth and the rest are generated by the build, extracted
 * from other ontologies, or previous releases. Opening the wrong one hands somebody a file whose
 * changes are destroyed at the next {@code make}, and nothing at the time suggests anything is
 * wrong - so the result says which file was opened and why.
 */
public class OpenFromGitHubAction extends OntoBoardAction {

    private static final long serialVersionUID = 1L;

    private static final String OPTION_URL = "url";
    private static final String OPTION_INTO = "into";
    private static final String OPTION_UPDATE = "update";

    private volatile String urlText = "";
    private volatile String intoText = "";
    private volatile boolean updateExisting = true;

    @Override
    protected String operationName() {
        return "Open from GitHub";
    }

    /** Nothing needs to be open to open something else. */
    @Override
    protected boolean needsAnOntology() {
        return false;
    }

    @Override
    protected boolean configure() {
        List<Parameter> parameters = Arrays.asList(
                Parameter.of(OPTION_URL, "Repository", Parameter.Kind.TEXT)
                        .required()
                        .help("Paste whatever you have: the address of the repository page, a "
                                + "link to a file or a branch inside it, the raw link, the SSH "
                                + "remote, or just owner/repo. A link to a particular file on a "
                                + "particular branch is taken as meaning that file on that "
                                + "branch. For example "
                                + "https://github.com/ISE-FIZKarlsruhe/mwo")
                        .build(),
                Parameter.of(OPTION_INTO, "Clone into", Parameter.Kind.FILE)
                        .required()
                        .defaultValue(defaultParentDirectory())
                        .help("The folder to put the checkout in. A directory named after the "
                                + "repository is created inside it, so pointing at the same "
                                + "folder every time collects your projects in one place. This "
                                + "is a real git checkout - you can branch, commit and push from "
                                + "it with your usual tools.")
                        .build(),
                Parameter.of(OPTION_UPDATE, "Update it if it is already there",
                        Parameter.Kind.FLAG)
                        .defaultValue("true")
                        .help("When a checkout of this repository is already in that folder, pull "
                                + "the latest commits before opening. The pull is fast-forward "
                                + "only, so it will refuse rather than touch local work - if you "
                                + "have uncommitted changes or your own commits, the checkout is "
                                + "opened as it stands and the result says so.")
                        .build());

        Map<String, String> chosen = ParameterDialog.show(getOWLWorkspace(), "Open from GitHub",
                "Clones an ontology repository with git and opens the file you are meant to "
                        + "edit. The checkout is a normal git working copy.",
                parameters);
        if (chosen == null) {
            return false;
        }
        urlText = chosen.get(OPTION_URL);
        intoText = chosen.get(OPTION_INTO);
        updateExisting = "true".equalsIgnoreCase(chosen.get(OPTION_UPDATE));
        return true;
    }

    @Override
    protected OperationResult run(OWLOntology ignored) {
        OperationResult.Builder result = OperationResult.of(operationName());

        GitHubUrl url;
        try {
            url = GitHubUrl.parse(urlText);
        } catch (IllegalArgumentException notGitHub) {
            return result.failed(notGitHub.getMessage()).build();
        }
        result.note("Repository: " + url);

        GitClone.Runner runner = GitClone.processRunner();
        if (!GitClone.isAvailable(runner)) {
            return result.failed(GitClone.gitMissing()).build();
        }

        File parent = new File(intoText.trim());
        if (!parent.isDirectory() && !parent.mkdirs()) {
            return result.failed("Could not create " + parent.getAbsolutePath()).build();
        }
        File checkout = GitClone.directoryFor(parent, url);

        if (GitClone.isCheckoutOf(checkout, url)) {
            result.note("Already cloned at " + checkout.getAbsolutePath());
            if (updateExisting) {
                updateInPlace(runner, checkout, result);
            } else {
                result.note("Left as it is - updating was turned off.");
            }
        } else if (checkout.exists()) {
            return result.failed(checkout.getAbsolutePath() + " already exists and is not a "
                    + "checkout of " + url.getFullName() + ". Choose a different folder to clone "
                    + "into.").build();
        } else {
            GitClone.Outcome cloned;
            try {
                cloned = runner.run(parent, GitClone.cloneCommand(url, checkout));
            } catch (IOException cannotRun) {
                return result.failed(GitClone.gitMissing()).build();
            }
            if (!cloned.isSuccess()) {
                return result.failed(GitClone.describeFailure(url, cloned)).build();
            }
            result.note("Cloned into " + checkout.getAbsolutePath());
            if (BackgroundRun.abandoned()) {
                return result.failed("Cloned to " + checkout.getAbsolutePath()
                        + ", but you stopped waiting, so nothing was opened.").build();
            }
        }

        String pathInRepo = switchToTheBranchTheLinkNamed(runner, checkout, url, result);
        File toOpen = fileToOpen(checkout, pathInRepo, result);
        if (toOpen == null) {
            return result.failed("The repository was cloned to " + checkout.getAbsolutePath()
                    + " but there is no ontology file in it.").build();
        }

        Boolean opened = openOnEventThread(toOpen);
        if (opened == null) {
            return result.failed("Protege could not open " + toOpen.getAbsolutePath()).build();
        }
        if (!opened.booleanValue()) {
            result.warn("Protege declined to open " + toOpen.getName()
                    + ". It is most likely already open in this window.");
            return result.summary("Cloned to " + checkout.getAbsolutePath()
                    + ", but the ontology was not opened.").build();
        }
        reportUnresolvedImports(toOpen, result);
        return result.summary(RepoLayout.explain(checkout, toOpen,
                RepoLayout.candidatesIn(checkout))).build();
    }

    /**
     * Says so when the ontology opened without half of itself.
     *
     * <p>An ontology whose imports did not resolve opens perfectly happily, and the several
     * thousand classes it was importing are simply absent: a term looks unused, a subclass axiom
     * points at nothing, and a reasoner reports no inconsistency because half the axioms are not
     * there. Nothing in the window says so.
     *
     * <p>Read from what the manager already has, so it costs nothing - no second load and no
     * network.
     */
    private void reportUnresolvedImports(File opened, OperationResult.Builder result) {
        OWLOntology active = getOWLModelManager().getActiveOntology();
        File catalog = opened.getParentFile() == null ? null
                : new File(opened.getParentFile(), "catalog-v001.xml");
        List<ImportHealth.Missing> missing = ImportHealth.missingFrom(active,
                getOWLModelManager().getOWLOntologyManager(), catalog);
        for (ImportHealth.Missing unresolved : missing) {
            result.warn(unresolved.explain());
        }
        if (!missing.isEmpty()) {
            result.warn("Until those resolve, the ontology is missing everything they contain - "
                    + "terms will look unused and a reasoner will not find problems that are "
                    + "really there.");
        }
    }

    /**
     * Checks out the branch the link named, once the repository can be asked which branches exist.
     *
     * <p>A GitHub URL gives no way to tell where a ref ends and a path begins:
     * {@code /tree/feature/x/src} is branch {@code feature/x} path {@code src} for one repository
     * and branch {@code feature} path {@code x/src} for another, and slash-bearing refs -
     * {@code feature/*}, {@code release/*}, {@code dependabot/*} - are everywhere. Splitting at
     * the first slash and passing that to {@code git clone} produced "the branch 'feature' is not
     * in this repository": a false statement about a branch nobody named, with nothing to suggest
     * the real one had been truncated.
     *
     * @return the path within the repository the link pointed at, once the branch is accounted for
     */
    private String switchToTheBranchTheLinkNamed(GitClone.Runner runner, File checkout,
            GitHubUrl url, OperationResult.Builder result) {
        if (url.getRefAndPath() == null) {
            return url.getPath();
        }
        List<String> branches;
        try {
            GitClone.Outcome listed = runner.run(checkout, GitClone.remoteBranchesCommand());
            branches = listed.isSuccess()
                    ? GitClone.remoteBranches(listed.getOutput())
                    : java.util.Collections.<String>emptyList();
        } catch (IOException cannotRun) {
            branches = java.util.Collections.<String>emptyList();
        }

        String[] resolved = url.resolveRef(branches);
        if (resolved[0] == null) {
            // No branch matches, so the whole remainder is a path on the default branch. Saying
            // nothing beats naming a branch the user never typed.
            result.note("Opened the default branch; no branch matched '" + url.getRefAndPath()
                    + "'.");
            return resolved[1];
        }
        try {
            GitClone.Outcome switched = runner.run(checkout,
                    GitClone.checkoutCommand(resolved[0]));
            if (switched.isSuccess()) {
                result.note("Branch: " + resolved[0]);
            } else {
                result.warn("Could not switch to " + resolved[0] + ", so the default branch is "
                        + "open instead: " + GitClone.lastLineOf(switched.getOutput()));
            }
        } catch (IOException cannotRun) {
            result.warn("Could not switch branch: " + cannotRun.getMessage());
        }
        return resolved[1];
    }

    /**
     * Which file, and why.
     *
     * <p>A path from the link wins, because it is a statement rather than a hint. Otherwise the
     * strict ODK detector, which refuses to guess; otherwise the general layout rules, which do
     * guess and say so.
     */
    private File fileToOpen(File checkout, String hintedPath, OperationResult.Builder result) {
        if (hintedPath != null && !hintedPath.trim().isEmpty()) {
            File hinted = new File(checkout, hintedPath.trim());
            if (hinted.isFile()) {
                result.note("Opening the file the link pointed at.");
                return hinted;
            }
        }
        try {
            OdkProjectLoader.Detected project = OdkProjectLoader.detect(checkout);
            result.note("ODK project: " + project.getTitle());
            return project.getEditFile();
        } catch (RuntimeException notOdk) {
            // Not an ODK repository, or an ambiguous one. The general rules cover both and the
            // explanation in the summary says the choice was a guess.
            return RepoLayout.ontologyIn(checkout, hintedPath);
        }
    }

    /**
     * Pulls, without ever touching local work.
     *
     * <p>{@code --ff-only}: a merge or a rebase here could conflict, and resolving a conflict is
     * not something a menu item should start on somebody's behalf. Refusing and saying so leaves
     * them with a checkout they still recognise.
     */
    private void updateInPlace(GitClone.Runner runner, File checkout,
            OperationResult.Builder result) {
        try {
            GitClone.Outcome pulled = runner.run(checkout,
                    Arrays.asList("git", "pull", "--ff-only"));
            if (pulled.isSuccess()) {
                result.note("Updated: " + GitClone.lastLineOf(pulled.getOutput()));
            } else {
                result.warn("Could not fast-forward, so nothing was changed: "
                        + GitClone.lastLineOf(pulled.getOutput())
                        + ". You have local commits or uncommitted changes; the checkout was "
                        + "opened as it stands.");
            }
        } catch (IOException cannotRun) {
            result.warn("Could not run git pull: " + cannotRun.getMessage());
        }
    }

    /**
     * Opens through Protege, on the dispatch thread.
     *
     * <p>{@code handleLoadFrom}, which is what File &gt; Open calls, rather than
     * {@code loadOntologyFromOntologyDocument}: the latter puts the ontology into the manager and
     * stops, so the model manager never hears about it, it does not become active and the class
     * hierarchy carries on showing whatever was there. That produced a "project opened" message
     * with nothing visible, which is exactly what was reported the first time round.
     *
     * @return whether Protege accepted it, or null if it threw
     */
    private Boolean openOnEventThread(final File file) {
        final AtomicReference<Boolean> opened = new AtomicReference<Boolean>();
        Runnable open = new Runnable() {
            @Override
            public void run() {
                try {
                    opened.set(Boolean.valueOf(
                            getOWLEditorKit().handleLoadFrom(file.toURI())));
                } catch (Exception couldNotLoad) {
                    opened.set(null);
                }
            }
        };
        if (SwingUtilities.isEventDispatchThread()) {
            open.run();
            return opened.get();
        }
        try {
            SwingUtilities.invokeAndWait(open);
        } catch (InterruptedException interrupted) {
            Thread.currentThread().interrupt();
            return null;
        } catch (InvocationTargetException thrown) {
            return null;
        }
        return opened.get();
    }

    /**
     * Where to put checkouts by default.
     *
     * <p>Beside whatever is already open when that is a git checkout - somebody who has one
     * ontology project cloned almost always wants the next one in the same place - and otherwise
     * a folder in the home directory, which exists on every platform and needs no permissions.
     */
    private String defaultParentDirectory() {
        try {
            OWLOntology active = getOWLModelManager() == null ? null
                    : getOWLModelManager().getActiveOntology();
            if (active != null) {
                File document = new File(getOWLModelManager().getOWLOntologyManager()
                        .getOntologyDocumentIRI(active).toURI());
                for (File directory = document.getParentFile(); directory != null;
                        directory = directory.getParentFile()) {
                    if (new File(directory, ".git").exists() && directory.getParentFile() != null) {
                        return directory.getParentFile().getAbsolutePath();
                    }
                }
            }
        } catch (RuntimeException notAFile) {
            // An unsaved or remote ontology says nothing about where projects live.
        }
        return new File(System.getProperty("user.home", "."), "ontology-projects")
                .getAbsolutePath();
    }
}
