package de.fizkarlsruhe.ise.ontoboard.odk;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.File;
import java.nio.file.Files;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.AddImport;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;
import org.semanticweb.owlapi.model.OWLOntologyManager;

/**
 * Noticing that an ontology opened without half of itself.
 *
 * <p>An ontology whose imports did not resolve opens perfectly happily: the hierarchy is there,
 * the file is there, and the thousands of classes it was importing are not. A term looks unused, a
 * subclass axiom points at nothing, and a reasoner reports no inconsistency because half the
 * axioms are absent. Nothing in the window says so, which is why it is worth saying here.
 */
class ImportHealthTest {

    private static final String PROJECT = "http://purls.helmholtz-metadaten.de/mwo/mwo";

    /** An ontology declaring an import, with none of them loaded. */
    private static OWLOntology declaring(OWLOntologyManager manager, String... importIris)
            throws Exception {
        OWLOntology ontology = manager.createOntology(IRI.create(PROJECT + ".owl"));
        for (String iri : importIris) {
            manager.applyChange(new AddImport(ontology,
                    manager.getOWLDataFactory().getOWLImportsDeclaration(IRI.create(iri))));
        }
        return ontology;
    }

    private static File catalogWith(File directory, String... pairs) throws Exception {
        String xml = null;
        for (int i = 0; i < pairs.length; i += 2) {
            xml = Catalog.withEntry(xml, pairs[i], pairs[i + 1]);
        }
        File catalog = new File(directory, "catalog-v001.xml");
        Files.write(catalog.toPath(), (xml == null ? Catalog.empty() : xml).getBytes("UTF-8"));
        return catalog;
    }

    // ---------- what is missing ----------

    @Test
    void animportThatLoadedIsNotReported(@TempDir File directory) throws Exception {
        OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
        OWLOntology ontology = declaring(manager, PROJECT + "/imports/iao_import.owl");
        manager.createOntology(IRI.create(PROJECT + "/imports/iao_import.owl"));

        assertTrue(ImportHealth.missingFrom(ontology, manager,
                catalogWith(directory)).isEmpty());
    }

    @Test
    void anImportThatDidNotLoadIsReported(@TempDir File directory) throws Exception {
        OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
        OWLOntology ontology = declaring(manager, PROJECT + "/imports/iao_import.owl");

        List<ImportHealth.Missing> missing = ImportHealth.missingFrom(ontology, manager,
                catalogWith(directory));

        assertEquals(1, missing.size());
        assertEquals(IRI.create(PROJECT + "/imports/iao_import.owl"),
                missing.get(0).getIri());
    }

    @Test
    void anOntologyWithNoImportsHasNothingMissing(@TempDir File directory) throws Exception {
        OWLOntologyManager manager = OWLManager.createOWLOntologyManager();

        assertTrue(ImportHealth.missingFrom(declaring(manager), manager,
                catalogWith(directory)).isEmpty());
    }

    @Test
    void nothingToLookAtIsNotAFailure() {
        assertTrue(ImportHealth.missingFrom(null, OWLManager.createOWLOntologyManager(), null)
                .isEmpty());
    }

    // ---------- three problems, three different answers ----------

    /**
     * The commonest ODK case by far: the module is generated by the build and gitignored, so a
     * fresh checkout has the catalog entry and not the file.
     */
    @Test
    void aCatalogEntryPointingAtAFileNobodyCommittedSaysToRunTheBuild(@TempDir File directory)
            throws Exception {
        OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
        OWLOntology ontology = declaring(manager, PROJECT + "/imports/iao_import.owl");
        File catalog = catalogWith(directory,
                PROJECT + "/imports/iao_import.owl", "imports/iao_import.owl");

        ImportHealth.Missing missing =
                ImportHealth.missingFrom(ontology, manager, catalog).get(0);

        assertTrue(missing.isInCatalog());
        assertFalse(missing.fileExists());
        assertTrue(missing.explain().contains("make"), missing.explain());
    }

    /** An IRI under the project's own domain is never published, so nothing can fetch it. */
    @Test
    void aProjectImportWithNoCatalogEntrySaysTheCatalogIsWhatResolvesIt(@TempDir File directory)
            throws Exception {
        OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
        OWLOntology ontology = declaring(manager, PROJECT + "/imports/iao_import.owl");

        ImportHealth.Missing missing = ImportHealth
                .missingFrom(ontology, manager, catalogWith(directory)).get(0);

        assertFalse(missing.isInCatalog());
        assertTrue(missing.explain().contains("catalog-v001.xml"), missing.explain());
        assertTrue(missing.explain().contains("never"), missing.explain());
    }

    /** A published ontology that did not download is a different problem with a different fix. */
    @Test
    void aPublishedOntologyThatDidNotDownloadIsBlamedOnTheNetwork(@TempDir File directory)
            throws Exception {
        OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
        OWLOntology ontology = declaring(manager, "http://purl.obolibrary.org/obo/ro.owl");

        ImportHealth.Missing missing = ImportHealth
                .missingFrom(ontology, manager, catalogWith(directory)).get(0);

        assertTrue(missing.explain().contains("proxy"), missing.explain());
        assertFalse(missing.explain().contains("catalog"),
                "no catalog entry is expected for a published ontology: " + missing.explain());
    }

    @Test
    void theExplanationAlwaysNamesTheImport(@TempDir File directory) throws Exception {
        OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
        OWLOntology ontology = declaring(manager, PROJECT + "/imports/iao_import.owl",
                "http://purl.obolibrary.org/obo/ro.owl");

        for (ImportHealth.Missing missing : ImportHealth.missingFrom(ontology, manager,
                catalogWith(directory))) {
            assertTrue(missing.explain().contains(missing.getIri().toString()),
                    missing.explain());
        }
    }

    // ---------- a catalog written the way ODK writes one ----------

    /**
     * The real thing nests its entries in a {@code <group id="odk-managed-catalog">}. Reading only
     * top-level entries would report every import of every ODK project as uncatalogued, which is
     * both wrong and the exact opposite of helpful.
     */
    @Test
    void entriesNestedInAnOdkGroupAreFound(@TempDir File directory) throws Exception {
        String odkCatalog = "<?xml version='1.0' encoding='UTF-8'?>\n"
                + "<catalog xmlns=\"urn:oasis:names:tc:entity:xmlns:xml:catalog\" "
                + "prefer=\"public\">\n"
                + "  <group id=\"odk-managed-catalog\" prefer=\"public\">\n"
                + "    <uri name=\"" + PROJECT + "/imports/iao_import.owl\" "
                + "uri=\"imports/iao_import.owl\" />\n"
                + "  </group>\n"
                + "</catalog>\n";
        File catalog = new File(directory, "catalog-v001.xml");
        Files.write(catalog.toPath(), odkCatalog.getBytes("UTF-8"));

        assertEquals("imports/iao_import.owl",
                Catalog.entryFor(odkCatalog, PROJECT + "/imports/iao_import.owl"));

        OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
        OWLOntology ontology = declaring(manager, PROJECT + "/imports/iao_import.owl");

        ImportHealth.Missing missing =
                ImportHealth.missingFrom(ontology, manager, catalog).get(0);

        assertTrue(missing.isInCatalog(), "the nested entry was not found");
    }

    @Test
    void aMissingCatalogFileIsNotTreatedAsAnEmptyOne(@TempDir File directory) throws Exception {
        OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
        OWLOntology ontology = declaring(manager, PROJECT + "/imports/iao_import.owl");

        ImportHealth.Missing missing = ImportHealth.missingFrom(ontology, manager,
                new File(directory, "no-catalog-here.xml")).get(0);

        assertFalse(missing.isInCatalog());
    }
}
